const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let STATE=null, selectedTicker=null, pollTimer=null, dragging=false, dragMoved=0;
const OBSERVED_QUOTES=new Map();let observationRefresh=0;
const FALLBACK_URL='data/recovery-os.json';
const notes=(()=>{try{return JSON.parse(localStorage.getItem('recoveryNotesV2')||'{}')}catch{return {}}})();
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2400)}
function money(v){return v==null?'N/A':'$'+Number(v).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}
function pct(v){return v==null?'N/A':`${v>0?'+':''}${Number(v).toFixed(1)}%`}
function safe(v,f='UNKNOWN'){return v==null||v===''?f:v}
function dataUrl(){return localStorage.getItem('recoveryRemoteUrl')||FALLBACK_URL}
async function loadState(force=false){try{const url=dataUrl(),join=url.includes('?')?'&':'?';const r=await fetch(url+join+'rev='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const next=await r.json();if(!STATE||force||next.meta.revision!==STATE.meta.revision){const old=STATE?.meta?.revision;STATE=next;selectedTicker=selectedTicker&&STATE.stocks.some(s=>s.ticker===selectedTicker)?selectedTicker:STATE.stocks[0]?.ticker;renderAll();if(old!=null&&old!==STATE.meta.revision)toast(`Portal updated · revision ${STATE.meta.revision}`)}setSyncState('SYNCED');return true}catch(e){console.warn('sync failed',e);setSyncState(location.protocol==='file:'?'LOCAL PREVIEW':'OFFLINE CACHE');if(!STATE&&'caches' in window){try{const c=await caches.match(FALLBACK_URL);if(c){STATE=await c.json();selectedTicker=STATE.stocks[0]?.ticker;renderAll()}}catch(_){}}return false}}
function setSyncState(v){const el=$('#worldState');if(el)el.textContent=v}
function qualifiedStocks(){return STATE.stocks.filter(s=>(s.universeClass||'QUALIFIED')==='QUALIFIED')}
function provisionalStocks(){return STATE.stocks.filter(s=>s.universeClass==='PROVISIONAL EXCEPTION REVIEW')}
function renderAll(){renderSystem();renderInspector(selectedTicker);renderHot();renderAlerts();renderScorecard();renderTracker();renderResearch();renderEvents();rebuildWorld()}
function trackerStateIsOld(){const stamp=trackerTimestamp(STATE?.meta?.scanTimestampET||STATE?.meta?.lastSuccessfulScan);return Number.isFinite(stamp)&&Date.now()-stamp>12*60*60*1000}
async function refreshCoverageChip(){try{const r=await fetch('data/information/coverage.json?fresh='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json(),p=(d.categories||[]).find(x=>x.id==='prices');if(!p)return;const s=p.statusCounts||{},current=(s.Current||0)+(s.Calculated||0),stale=s.Stale||0,partial=s.Partial||0,unavailable=s.Unavailable||0,chip=$('#coverageChip');chip.textContent=`PRICES ${current} CUR · ${stale} STALE`;chip.title=`${p.covered}/${p.total} price dossiers · ${partial} partial · ${unavailable} unavailable · last attempt ${p.lastAttemptedUpdate||'unknown'}`;chip.classList.toggle('warn',stale+unavailable>current)}catch(e){const chip=$('#coverageChip');chip.textContent=STATE?.meta?.priceCoverage?.split('—')[0].trim()||'DATA UNKNOWN';chip.title='Current coverage report unavailable'}}
function renderSystem(){const m=STATE.meta,old=trackerStateIsOld(),marketRefresh=m.lastSuccessfulMarketRefresh||'No current market refresh recorded';$('#sessionChip').textContent=(old?'SAVED SESSION · ':'SESSION · ')+m.marketSession;$('#marketChip').textContent=(old?'SAVED MARKET · ':'MARKET · ')+STATE.market.classification;$('#coverageChip').textContent='CHECKING DATA…';$('#revisionChip').textContent='REV '+m.revision;$('#lastScan').textContent='MARKET DATA · '+marketRefresh+' · THESIS SCAN · '+m.lastSuccessfulScan;$('#trackerMeta').textContent=`${qualifiedStocks().length} QUALIFIED · ${provisionalStocks().length} PROVISIONAL · ${STATE.scorecard.actionable} ACTIONABLE · REV ${m.revision}`;$('#worldCount').textContent=qualifiedStocks().length+' + '+provisionalStocks().length+'P';$('#systemSummary').innerHTML=`<b>${m.dataLabel}</b><br><br>Latest market-data refresh: ${marketRefresh}<br>Last full thesis scan: ${m.lastSuccessfulScan}<br>Tracker snapshot: ${m.generatedAt||'unknown'}<br>Storage: ${m.storage}<br>State revision: ${m.revision}<br>Source: ${dataUrl()}`;$('#remoteUrl').value=localStorage.getItem('recoveryRemoteUrl')||'';$('#pollSeconds').value=localStorage.getItem('recoveryPollSeconds')||m.pollSeconds||60;refreshCoverageChip()}
function stock(t){return STATE.stocks.find(x=>x.ticker===t)}
function trackerTimestamp(value){return window.RecoveryFreshness.stamp(value)}
function latestQuote(x){const observed=OBSERVED_QUOTES.get(x.ticker),base={price:x.latestPrice,asOf:x.quoteAsOf,source:'Recovery OS tracker',stamp:trackerTimestamp(x.quoteAsOf)};return observed&&observed.stamp>base.stamp?observed:base}
function quoteLabel(x,q=latestQuote(x)){const ah=x.marketData?.afterHoursPrice;return q.asOf+(Number.isFinite(ah)?` · AH ${money(ah)} @ ${x.marketData.afterHoursAsOf||'snapshot'}`:'')}
function latestSinceAdded(x){const q=latestQuote(x);return Number.isFinite(q.price)&&Number.isFinite(x.discoveryPrice)&&x.discoveryPrice!==0?(q.price/x.discoveryPrice-1)*100:x.sinceAddedPct}
async function refreshTrackerObservations(){const run=++observationRefresh,state=STATE;if(!state||typeof researchBundle!=='function')return;const results=await Promise.allSettled(state.stocks.map(async x=>{const b=await researchBundle(x.ticker,{refresh:true}),q=b?.quote;if(!Number.isFinite(q?.price))return;const source=b?.priceSource||{},asOf=window.RecoveryFreshness.effective(b),stamp=trackerTimestamp(asOf);if(stamp>trackerTimestamp(x.quoteAsOf))OBSERVED_QUOTES.set(x.ticker,{price:q.price,asOf:'Research snapshot · '+safe(source.date||String(asOf||'').slice(0,10),'date unavailable')+(source.publisher?' · '+source.publisher:''),source:source.publisher||q.source||'Research source',stamp})}));if(run!==observationRefresh||STATE!==state)return;if(results.some(r=>r.status==='fulfilled')){renderInspector(selectedTicker);renderTracker();if($('#room').classList.contains('show')&&selectedTicker){const x=stock(selectedTicker),q=latestQuote(x);$('#rPrice').textContent=money(q.price);$('#rQuote').textContent=quoteLabel(x,q);renderStateMatrix(x)}}}
function renderInspector(t){const x=stock(t);if(!x)return;const q=latestQuote(x);selectedTicker=x.ticker;$('#iTicker').textContent=x.ticker;$('#iCompany').textContent=x.company;$('#iTier').textContent=x.tier;$('#iPrice').textContent=money(q.price);$('#iAsOf').textContent=quoteLabel(x,q);$('#iDirection').textContent=(q.stamp>trackerTimestamp(x.quoteAsOf)?'TRACKER · ':'')+x.direction;$('#iScore').textContent=x.score??'N/A';$('#iProgress').textContent=(x.progress??0)+'%';$('#scoreRing').style.setProperty('--p',x.score??0);$('#progressRing').style.setProperty('--p',x.progress??0);$('#iStatus').textContent=x.status;$('#iEntry').textContent=x.entryEligible;$('#iCrisis').textContent=x.crisis.summary;$('#iCatalyst').textContent=x.catalyst.summary;$('#iBlocker').textContent=x.blocker;world.selected=STATE.stocks.findIndex(s=>s.ticker===t)}
function renderHot(){const xs=[...qualifiedStocks()].sort((a,b)=>(b.score??-1)-(a.score??-1));$('#hotList').innerHTML=xs.slice(0,5).map((x,i)=>`<div class="hot-card" data-ticker="${x.ticker}"><div class="rank">0${i+1}</div><div><b>${x.ticker} · ${x.company}</b><small>${x.status} · ${x.tier} · ${x.entryEligible==='YES'?'ENTRY ELIGIBLE':'BLOCKED'}</small></div><div class="scoretag">${x.score??'N/A'}</div></div>`).join('');$$('.hot-card').forEach(e=>e.onclick=()=>openRoom(e.dataset.ticker))}
function renderAlerts(){$('#alertList').innerHTML=STATE.alerts.map(a=>`<div class="alert ${a.severity}"><div class="alert-dot"></div><div><h4>${a.ticker} // ${a.title}</h4><p>${a.text}</p><time>${a.time}</time></div></div>`).join('')}
function renderScorecard(){const labels={qualified:'Qualified',provisionalExceptionReview:'Provisional',researchQueue:'Research',actionable:'Actionable',developing:'Developing',triggeredEver:'Ever triggered',invalidated:'Invalidated',paperOpen:'Paper open',paperResolved:'Paper resolved'};$('#scoreGrid').innerHTML=Object.entries(labels).map(([k,l])=>`<div class="scorebox"><label>${l}</label><strong>${STATE.scorecard[k]??0}</strong></div>`).join('')}
function renderTracker(){const xs=[...STATE.stocks].sort((a,b)=>(b.score??-1)-(a.score??-1));$('#trackerRows').innerHTML=xs.map((x,i)=>{const q=latestQuote(x);return `<tr data-ticker="${x.ticker}"><td>${i+1}</td><td><b>${x.ticker}</b><br><span style="color:#4e6b7d">${x.company}</span></td><td>${x.dateAdded}</td><td>${money(x.discoveryPrice)}</td><td>${money(q.price)}<br><span style="color:#547184">${pct(latestSinceAdded(x))}</span><br><span style="color:#587486;font-size:8px">${safe(quoteLabel(x,q))}</span></td><td>${x.status}<br><span class="pill ${x.tier.includes('SPEC')?'spec':''}">${x.tier}</span><br><span style="color:#587486;font-size:8px">${x.universeClass||'QUALIFIED'}</span></td><td>${x.score??'N/A'}</td><td>${x.progress}%</td><td>${x.entryEligible}</td><td>${x.blocker}</td></tr>`}).join('');$$('#trackerRows tr').forEach(r=>r.onclick=()=>openRoom(r.dataset.ticker))}
function renderResearch(){$('#researchList').innerHTML=STATE.researchQueue.map(x=>`<div class="research-card"><b>${x.ticker}</b><small>${x.company} · ${x.theme}</small><p>${x.reason}</p></div>`).join('')}
function renderEvents(){$('#eventList').innerHTML=[...STATE.events].reverse().map(e=>`<div class="event"><b>${e.ticker} // ${e.title}</b><time>${e.time} · ${e.type}</time>${e.detail}</div>`).join('')}
function openRoom(t){const x=stock(t);if(!x)return;const q=latestQuote(x);renderInspector(t);$('#rTicker').textContent=x.ticker;$('#rCompany').textContent=x.company+' · '+x.theme;$('#rStatus').textContent=x.status;$('#coreTicker').textContent=x.ticker;$('#rPrice').textContent=money(q.price);$('#rQuote').textContent=quoteLabel(x,q);$('#stageData').innerHTML=`CLASS ${x.universeClass||'QUALIFIED'}<br>ENTRY ${x.entryEligible}<br>TIER ${x.tier}<br>RISK ${x.risk}<br>EVIDENCE ${x.evidenceQuality}<br>SCORE ${x.score??'N/A'}<br>PROGRESS ${x.progress}%`;renderChart(x);renderStateMatrix(x);renderTimeline(x);renderChecks(x);renderRiskMap(x);renderCatalyst(x);renderEvidence(x);renderChanges(x);renderThesis(x);renderPerformance(x);$('#operatorNote').value=notes[x.ticker]||'';$('#room').classList.add('show');document.body.style.overflow='hidden'}
function closeRoom(){$('#room').classList.remove('show');document.body.style.overflow=''}
function renderChart(x){const pts=x.priceSeries||[];if(!pts.length){$('#chart').innerHTML='<div style="color:#587486;font-size:9px">NO VERIFIED PRICE SERIES</div>';return}const w=500,h=160,p=10,vals=pts.map(d=>d.close),min=Math.min(...vals),max=Math.max(...vals),range=max-min||1,xy=vals.map((v,i)=>[p+i*(w-2*p)/(vals.length-1),h-p-(v-min)*(h-2*p)/range]),path=xy.map((q,i)=>(i?'L':'M')+q[0].toFixed(1)+' '+q[1].toFixed(1)).join(' '),area=path+` L ${xy.at(-1)[0]} ${h-p} L ${xy[0][0]} ${h-p} Z`;$('#chart').innerHTML=`<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><defs><linearGradient id="ag" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#7ceaff" stop-opacity=".20"/><stop offset="1" stop-color="#7ceaff" stop-opacity="0"/></linearGradient></defs><path d="${area}" fill="url(#ag)"/><path d="${path}" fill="none" stroke="#7ceaff" stroke-width="2" vector-effect="non-scaling-stroke"/><text x="8" y="13" fill="#587486" font-size="9">${money(max)}</text><text x="8" y="${h-5}" fill="#587486" font-size="9">${money(min)}</text></svg>`}
function renderStateMatrix(x){const m=[['Score',x.score??'N/A'],['Progress',x.progress+'%'],['Entry',x.entryEligible],['Risk',x.risk],['Evidence',x.evidenceQuality],['Since add',pct(latestSinceAdded(x))],['52W low',money(x.technical.low52)],['Above low',pct(x.technical.aboveLowPct)]];$('#stateMatrix').innerHTML=m.map(q=>`<div class="micro"><label>${q[0]}</label><b>${q[1]}</b></div>`).join('')}
function renderTimeline(x){const rows=[['CRISIS',x.crisis.summary],['STATE',x.crisis.state],['CATALYST',x.catalyst.summary],['NEXT MILESTONE',safe(x.catalyst.nextMilestone)],['EXPIRY / REVIEW',safe(x.setup.expiry,'OPEN')]];$('#crisisTimeline').innerHTML=rows.map(r=>`<div class="timeline-row"><b>${r[0]}</b><br>${r[1]}</div>`).join('')}
function renderChecks(x){$('#entryChecks').innerHTML=x.checklist.map(c=>`<div class="check ${c.state}"><span class="dot"></span><span>${c.name}</span><em>${c.state} · ${c.weight}%</em></div>`).join('')}
function renderRiskMap(x){const s=x.setup;if(s.trigger==null||s.t1==null){$('#riskMap').innerHTML=`<div class="rr"><div class="empty">R/R UNDEFINED — ENTRY GATE BLOCKED</div></div><div class="timeline-row"><b>Technical invalidation</b><br>${money(s.invalidation)} · ${s.invalidationBasis}</div><div class="timeline-row"><b>Event restriction</b><br>${s.eventRestriction}</div>`;return}$('#riskMap').innerHTML='<div class="timeline-row">Defined setup levels loaded.</div>'}
function renderCatalyst(x){const c=x.catalyst;$('#catalystNetwork').innerHTML=`<div class="timeline-row"><b>${c.state}</b><br>${c.summary}</div><div class="timeline-row"><b>NEXT</b><br>${safe(c.nextMilestone)}${c.nextDate?' · '+c.nextDate:''}</div><div class="timeline-row"><b>FUNDAMENTAL INVALIDATION</b><br>${x.setup.fundamentalInvalidation}</div>`}
function renderEvidence(x){$('#evidenceFeed').innerHTML=x.evidence.map(e=>`<div class="evidence-row"><b>${e.sourceType} · ${e.title}</b><br>${e.claim}<br>${e.url?`<a href="${e.url}" target="_blank" rel="noopener">OPEN SOURCE ↗</a>`:''}</div>`).join('')||'<div class="evidence-row">NO EVIDENCE LOADED</div>'}
function renderChanges(x){$('#changeFeed').innerHTML=(x.changes||[]).map((c,i)=>`<div class="change-row"><b>${String(i+1).padStart(2,'0')}</b> · ${c}</div>`).join('')}
function renderThesis(x){$('#thesisChecks').innerHTML=x.thesisChecklist.map(c=>`<div class="check ${c.state==='YES'?'COMPLETE':c.state==='NO'?'NOT MET':'UNKNOWN'}"><span class="dot"></span><span>${c.name}</span><em>${c.state}</em></div>`).join('')}
function renderPerformance(x){const p=x.performance,rows=[['Outcome',p.outcome],['MFE',pct(p.mfePct)],['MAE',pct(p.maePct)],['Paper R',p.paperR??'N/A'],['Benchmark excess',pct(p.benchmarkExcessPct)]];$('#performanceLab').innerHTML=rows.map(r=>`<div class="timeline-row"><b>${r[0]}</b><br>${r[1]}</div>`).join('')}
$('#operatorNote').addEventListener('input',e=>{if(!selectedTicker)return;notes[selectedTicker]=e.target.value;localStorage.setItem('recoveryNotesV2',JSON.stringify(notes))});
const canvas=$('#worldCanvas'),ctx=canvas.getContext('2d'),world={rx:-.18,ry:.35,zoom:1,selected:0,nodes:[],auto:true,lastX:0,lastY:0};
function rebuildWorld(){if(!STATE)return;world.nodes=STATE.stocks.map((s,i)=>{const a=i/STATE.stocks.length*Math.PI*2;return{x:Math.cos(a)*1.8,y:(i%2?-.52:.50)+(i-(STATE.stocks.length-1)/2)*.025,z:Math.sin(a)*1.8,ticker:s.ticker,type:s.universeClass==='PROVISIONAL EXCEPTION REVIEW'?'spec':s.status==='EARLY REVERSAL'?'developing':'watch'}});world.selected=Math.max(0,STATE.stocks.findIndex(s=>s.ticker===selectedTicker))}
function resizeCanvas(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0)}addEventListener('resize',resizeCanvas);resizeCanvas();
function rot(p){let{x,y,z}=p,cy=Math.cos(world.ry),sy=Math.sin(world.ry),cx=Math.cos(world.rx),sx=Math.sin(world.rx),x1=x*cy-z*sy,z1=x*sy+z*cy;return{x:x1,y:y*cx-z1*sx,z:y*sx+z1*cx}}
function proj(p,w,h){const d=5.3,s=(255*world.zoom)/(d-p.z);return{x:w/2+p.x*s,y:h/2+p.y*s,scale:s/85}}
function drawWorld(){if(document.hidden||document.body.classList.contains('research-open')){setTimeout(()=>requestAnimationFrame(drawWorld),250);return}const w=canvas.clientWidth,h=canvas.clientHeight;if(world.auto&&!dragging&&!matchMedia('(prefers-reduced-motion: reduce)').matches)world.ry+=.0007;ctx.clearRect(0,0,w,h);for(let i=0;i<80;i++){ctx.fillStyle=`rgba(160,230,255,${.03+((i*13)%8)/80})`;ctx.fillRect((i*137.3+w*.07)%w,(i*79.7+h*.11)%h,1,1)}let hor=h*.64;ctx.strokeStyle='rgba(90,205,235,.055)';for(let i=-10;i<=10;i++){ctx.beginPath();ctx.moveTo(w/2+i*18,hor);ctx.lineTo(w/2+i*98,h);ctx.stroke()}for(let j=0;j<9;j++){let t=j/8,y=hor+(h-hor)*(t*t);ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}const points=world.nodes.map((n,i)=>({n,i,r:rot(n)})).map(o=>({...o,p:proj(o.r,w,h)})).sort((a,b)=>a.r.z-b.r.z);ctx.strokeStyle='rgba(124,234,255,.055)';for(let i=0;i<points.length;i++)for(let j=i+1;j<points.length;j++)if((i+j)%3===0){ctx.beginPath();ctx.moveTo(points[i].p.x,points[i].p.y);ctx.lineTo(points[j].p.x,points[j].p.y);ctx.stroke()}points.forEach(o=>{const sel=o.i===world.selected,col=o.n.type==='spec'?'240,120,190':o.n.type==='developing'?'167,139,250':'124,234,255',rad=(sel?10:7)*Math.max(.72,Math.min(1.25,o.p.scale));ctx.shadowBlur=sel?26:12;ctx.shadowColor=`rgba(${col},.7)`;ctx.beginPath();ctx.arc(o.p.x,o.p.y,rad,0,Math.PI*2);ctx.fillStyle=`rgba(${col},${sel?1:.74})`;ctx.fill();ctx.shadowBlur=0;ctx.font=`${sel?'700':'600'} ${sel?12:10}px -apple-system,system-ui`;ctx.textAlign='center';ctx.fillStyle=sel?'#effeff':'#9fc9d7';ctx.fillText(o.n.ticker,o.p.x,o.p.y-rad-9)});requestAnimationFrame(drawWorld)}drawWorld();
canvas.addEventListener('pointerdown',e=>{dragging=true;dragMoved=0;world.lastX=e.clientX;world.lastY=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!dragging)return;let dx=e.clientX-world.lastX,dy=e.clientY-world.lastY;dragMoved+=Math.abs(dx)+Math.abs(dy);world.ry+=dx*.008;world.rx=Math.max(-.95,Math.min(.65,world.rx+dy*.005));world.lastX=e.clientX;world.lastY=e.clientY});canvas.addEventListener('pointerup',e=>{dragging=false;if(dragMoved<10)hitNode(e)});canvas.addEventListener('pointercancel',()=>dragging=false);
function hitNode(e){const r=canvas.getBoundingClientRect(),w=r.width,h=r.height,mx=e.clientX-r.left,my=e.clientY-r.top;let best=null,bd=999;world.nodes.forEach((n,i)=>{const p=proj(rot(n),w,h),d=Math.hypot(mx-p.x,my-p.y);if(d<30&&d<bd){bd=d;best=i}});if(best!=null){const t=STATE.stocks[best].ticker;renderInspector(t);openRoom(t)}}
function go(id){document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'});$$('[data-go]').forEach(b=>b.classList.toggle('active',b.dataset.go===id))}$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
$('#openRoom').onclick=()=>openRoom(selectedTicker);$('#roomBack').onclick=closeRoom;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!document.body.classList.contains('research-open')){closeRoom();closeSettings()}});function openSettings(){$('#settings').classList.add('show')}function closeSettings(){$('#settings').classList.remove('show')}$('#settingsBtn').onclick=openSettings;$('#settingsRail').onclick=openSettings;$('#settingsMobile').onclick=openSettings;$('#settingsClose').onclick=closeSettings;
$('#saveSettings').onclick=()=>{const u=$('#remoteUrl').value.trim(),p=Math.max(30,Math.min(3600,Number($('#pollSeconds').value)||60));if(u)localStorage.setItem('recoveryRemoteUrl',u);else localStorage.removeItem('recoveryRemoteUrl');localStorage.setItem('recoveryPollSeconds',p);schedulePolling();loadState(true);closeSettings();toast('Sync settings saved')};$('#syncBtn').onclick=()=>window.RecoveryRefresh?window.RecoveryRefresh.refresh(true):loadState(true);$('#scanCommand').onclick=()=>toast('Run SCAN NOW in ChatGPT · connected scans publish automatically');$('#changesCommand').onclick=()=>{go('history');toast('Showing latest append-only changes')};$('#hotCommand').onclick=()=>go('command');$('#scoreCommand').onclick=()=>{go('command');toast('Scorecard is in Command Center')};
$('#exportCommand').onclick=()=>{if(!STATE)return;const blob=new Blob([JSON.stringify(STATE,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`recovery-os-rev-${STATE.meta.revision}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Tracker checkpoint exported')};$('#sharePortal').onclick=async()=>{try{if(navigator.share)await navigator.share({title:'Recovery OS',text:'Crisis-to-Recovery Command Portal',url:location.href});else{await navigator.clipboard.writeText(location.href);toast('Portal link copied')}}catch(e){}};
function schedulePolling(){clearInterval(pollTimer);const sec=Math.max(30,Number(localStorage.getItem('recoveryPollSeconds')||STATE?.meta?.pollSeconds||60));pollTimer=setInterval(()=>{if(document.hidden)return;loadState(false);window.RecoveryRefresh?.refresh()},sec*1000)}
if(!window.RECOVERY_REVIEW&&'serviceWorker' in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(console.warn);window.addEventListener('market-atlas-ready',refreshTrackerObservations);loadState(true).then(()=>{schedulePolling();setTimeout(refreshTrackerObservations,0)});setTimeout(()=>$('#boot').classList.add('off'),1700);
