function financialTable(rows){if(!rows?.length)return'<div class="empty-panel">No statements are loaded for this period view.</div>';return `<div class="data-table-wrap"><table class="data-table"><thead><tr><th>Period</th><th>Revenue</th><th>Gross Margin</th><th>Operating Inc.</th><th>Op Margin</th><th>Net Income</th><th>Net Margin</th><th>EPS</th><th>Op Cash Flow</th><th>CapEx</th><th>Free Cash Flow</th><th>LT Debt</th><th>Diluted Shares</th><th>Current Ratio</th><th>Source</th></tr></thead><tbody>${rows.map(x=>`<tr><td><b>${esc(x.period)}</b><br>${esc(x.endDate||'')}</td><td>${fmtMoney(x.revenue,true)}</td><td>${fmtPct(x.grossMarginPct)}</td><td>${fmtMoney(x.operatingIncome,true)}</td><td>${fmtPct(x.operatingMarginPct)}</td><td>${fmtMoney(x.netIncome,true)}</td><td>${fmtPct(x.netMarginPct)}</td><td>${x.dilutedEPS==null?'N/A':'$'+Number(x.dilutedEPS).toFixed(2)}</td><td>${fmtMoney(x.operatingCashFlow,true)}</td><td>${fmtMoney(x.capitalExpenditure,true)}</td><td>${fmtMoney(x.freeCashFlow,true)}</td><td>${fmtMoney(x.longTermDebt,true)}</td><td>${fmtNum(x.dilutedShares,0)}</td><td>${x.currentRatio==null?'N/A':Number(x.currentRatio).toFixed(2)}</td><td>${x.source?`<a href="${esc(x.source)}" target="_blank" rel="noopener">SEC ↗</a>`:'N/A'}</td></tr>`).join('')}</tbody></table></div>`}
function renderFundamentals(b){
 const f=b.financials||{},rows=f.quarterly||[],val=f.valuation||{},latest=rows[0]||{};
 const pctVal=v=>v==null?'N/A':fmtPct(v,1);
 return `<section class="ex-card full"><h3>FINANCIALS / FUNDAMENTALS <span class="hint">REPORTED + CALCULATED</span></h3><div class="seg" id="financialTabs" style="margin-bottom:9px"><button data-fin-view="quarterly" class="on">QUARTERLY</button><button data-fin-view="annual">ANNUAL</button></div><div id="financialTableWrap">${financialTable(rows)}</div><div class="source-note">Fiscal period, currency and filing date are preserved. Margins/current ratio are MODEL CALCULATIONS from reported values. CapEx/FCF remain N/A when the accessible standardized statement feed does not provide a compatible tag.</div></section>
 <section class="ex-card half"><h3>BALANCE SHEET / CAPITAL STRUCTURE</h3><div class="state-row"><label>Current assets</label><b>${fmtMoney(latest.currentAssets,true)}</b></div><div class="state-row"><label>Current liabilities</label><b>${fmtMoney(latest.currentLiabilities,true)}</b></div><div class="state-row"><label>Cash</label><b>${fmtMoney(latest.cash,true)}</b></div><div class="state-row"><label>Total debt</label><b>${fmtMoney(latest.totalDebt,true)}</b></div><div class="state-row"><label>Long-term debt</label><b>${fmtMoney(latest.longTermDebt,true)}</b></div><div class="state-row"><label>Net debt</label><b>${fmtMoney(latest.netDebt,true)}</b></div><div class="state-row"><label>Diluted shares</label><b>${fmtNum(latest.dilutedShares,0)}</b></div><div class="source-note">Debt maturities, buybacks and dividends are shown only when a compatible source is connected; missing fields are not inferred.</div></section>
 <section class="ex-card half"><h3>VALUATION / CAPITAL EFFICIENCY</h3><div class="metric-grid">${[['P/E',val.priceToEarnings],['Forward P/E',val.forwardPE],['Price / Sales',val.priceToSales],['EV / Revenue',val.evRevenue],['EV / EBITDA',val.evEbitda],['Price / Book',val.priceToBook],['FCF Yield %',val.freeCashFlowYield],['Dividend Yield %',val.dividendYield],['ROA %',val.returnOnAssets],['ROE %',val.returnOnEquity],['Debt / Equity',val.debtToEquity],['Current Ratio',val.currentRatio],['Quick Ratio',val.quickRatio]].map(([k,v])=>`<div class="stat"><label>${k}</label><b>${v==null?'N/A':fmtNum(v,2)}</b></div>`).join('')}</div><div class="state-row"><label>Enterprise value</label><b>${fmtMoney(val.enterpriseValue,true)}</b></div><div class="state-row"><label>TTM free cash flow</label><b>${fmtMoney(val.freeCashFlow,true)}</b></div><div class="empty-panel" style="margin-top:10px"><strong>${esc(val.status||'Some valuation metrics unavailable')}</strong>${val.asOf?`Ratio date ${esc(val.asOf)}. `:''}Unavailable values stay null rather than being reconstructed from incompatible periods or stale analyst estimates.</div></section>`
}
function renderFund(b){
 const f=b.fund||{},holdings=f.holdings||[];
 return `<section class="ex-card full"><h3>ETF FUND PROFILE <span class="hint">FUND-SPECIFIC DATA</span></h3><div class="metric-grid"><div class="stat"><label>Benchmark</label><b>${esc(f.benchmark||'N/A')}</b></div><div class="stat"><label>Assets</label><b>${fmtMoney(f.assets,true)}</b></div><div class="stat"><label>Expense Ratio</label><b>${f.expenseRatio==null?'N/A':fmtPct(Number(f.expenseRatio)*100,2)}</b></div><div class="stat"><label>Holdings</label><b>${f.numHoldings??holdings.length??'N/A'}</b></div><div class="stat"><label>Top 10 concentration</label><b>${f.top10Concentration==null?'N/A':fmtPct(Number(f.top10Concentration)*100,1)}</b></div><div class="stat"><label>Avg daily volume</label><b>${fmtNum(f.avgDailyVolume,0)}</b></div><div class="stat"><label>Category / focus</label><b>${esc([f.category,f.focus].filter(Boolean).join(' · ')||'N/A')}</b></div><div class="stat"><label>Distribution</label><b>${esc(f.distributionFrequency||'N/A')}</b></div></div>${holdings.length?`<div class="data-table-wrap" style="margin-top:10px"><table class="data-table"><thead><tr><th>Rank</th><th>Holding</th><th>Weight</th><th>Market Value</th><th>Effective</th></tr></thead><tbody>${holdings.slice(0,20).map(h=>`<tr ${h.ticker?`data-open-symbol="${esc(h.ticker)}"`:''}><td>${h.rank??'—'}</td><td><b>${esc(h.ticker||'—')}</b><br>${esc(h.name||'')}</td><td>${h.weight==null?'N/A':fmtPct(Number(h.weight)*100,2)}</td><td>${fmtMoney(h.marketValue,true)}</td><td>${esc(h.effectiveDate||f.effectiveDate||'UNKNOWN')}</td></tr>`).join('')}</tbody></table></div>`:''}<div class="empty-panel" style="margin-top:10px"><strong>${esc(f.status||'FUND DATA LIMITED')}</strong>Company earnings and corporate valuation panels are intentionally replaced with fund-specific fields for ETFs.${f.processedDate?` Processed ${esc(f.processedDate)}.`:''}</div></section>`
}
