function renderStock(b){const p=b.profile||{},q=b.quote||{},t=p.ticker||currentTicker,tr=tracked(t),isETF=(p.typeCode==='ETF'||String(p.securityType).toUpperCase().includes('ETF'));
 const move=q.changePct==null?'':`<span class="${q.changePct>=0?'up':'down'}">${q.change>=0?'+':''}${fmtMoney(q.change)} · ${fmtPct(q.changePct,2)}</span>`;
 const perf=q.performancePct||{}; const matters=(b.whatMatters||[]).map(x=>`<div class="matter"><span class="ex-badge ${x.type==='LIMITATION'?'warn':x.type==='INTERPRETATION'?'model':''}">${esc(x.type)}</span>${esc(x.text)}</div>`).join('')||'<div class="matter">No current summary available.</div>';
 const html=`<div class="ex-page-head"><div><span class="ex-badge">STOCK RESEARCH</span>${tr?'<span class="ex-badge model">RECOVERY TRACKED</span>':'<span class="ex-badge">GENERAL RESEARCH</span>'}</div><div class="ex-statusline"><span id="exMarketNow">MARKET ${esc(String(MARKET_STATUS?.market||'UNKNOWN').toUpperCase())} · ${esc(MARKET_STATUS?.serverTime?ago(MARKET_STATUS.serverTime):'STATUS UNKNOWN')}</span><br>${esc(q.dataState||'DATA UNAVAILABLE')} · ${esc(q.timestamp||'NO QUOTE TIMESTAMP')}</div></div>
 <div class="ex-grid">
 <section class="ex-card full"><div class="stock-identity"><div><div class="stock-symbol"><div class="mark">${esc(t)}</div><div><h2>${esc(t)}</h2><small>${esc(p.name||'UNKNOWN')} · ${esc(p.exchange||'UNKNOWN EXCHANGE')} · ${esc(p.securityType||'UNKNOWN TYPE')}</small></div></div><div class="stock-description">${esc(p.description||'No business description is available for this cached record.')}</div></div><div class="stock-price"><strong>${fmtMoney(q.price)}</strong><div>${move}</div><small>Regular ${fmtMoney(q.regular)}${q.preMarket!=null?` · Pre ${fmtMoney(q.preMarket)}`:''}${q.afterHours!=null?` · After ${fmtMoney(q.afterHours)}`:(q.extended!=null?` · Extended ${fmtMoney(q.extended)}`:'')}<br>${esc(q.timestamp||'Quote unavailable')}${q.extendedTimestamp?`<br>${esc(q.extendedTimestamp)}`:''}</small></div></div><div id="stockActions" style="margin-top:13px;display:flex;gap:7px;flex-wrap:wrap"></div></section>
 <section class="ex-card wide"><h3>WHAT MATTERS NOW <span class="hint">FACTS / DATA / INTERPRETATION SEPARATED</span></h3>${matters}</section>
 <section class="ex-card"><h3>PROFILE</h3><div class="state-row"><label>Sector</label><b>${esc(p.sector||'N/A')}</b></div><div class="state-row"><label>Industry</label><b>${esc(p.industry||p.sicDescription||'N/A')}</b></div><div class="state-row"><label>Market cap ⓘ</label><b title="${esc(DEFINITIONS['Market cap'])}">${fmtMoney(p.marketCap,true)}</b></div><div class="state-row"><label>Currency</label><b>${esc(p.currency||'N/A')}</b></div><div class="state-row"><label>CIK</label><b>${esc(p.cik||'N/A')}</b></div></section>
 <section class="ex-card full"><h3>PRICE / LIQUIDITY SNAPSHOT <span class="hint">TIMESTAMPED MARKET DATA</span></h3><div class="metric-grid"><div class="stat"><label>Day Range</label><b>${q.dayRange?`${fmtMoney(q.dayRange[0])} – ${fmtMoney(q.dayRange[1])}`:'N/A'}</b></div><div class="stat"><label>52W Range</label><b>${q.range52w?`${fmtMoney(q.range52w[0])} – ${fmtMoney(q.range52w[1])}`:'N/A'}</b></div><div class="stat"><label>From 52W High</label><b>${fmtPct(q.from52wHighPct)}</b></div><div class="stat"><label>Above 52W Low</label><b>${fmtPct(q.above52wLowPct)}</b></div><div class="stat"><label>Volume</label><b>${fmtNum(q.volume,0)}</b></div><div class="stat"><label>20D Avg Vol</label><b>${fmtNum(q.avgVolume20,0)}</b></div><div class="stat"><label>20D Avg $ Volume</label><b>${fmtMoney(q.avgDollarVolume20,true)}</b></div><div class="stat"><label>Relative Volume ⓘ</label><b title="${esc(DEFINITIONS['Relative volume'])}">${q.relativeVolume==null?'N/A':Number(q.relativeVolume).toFixed(2)+'×'}</b></div><div class="stat"><label>Performance</label><b>${Object.entries(perf).slice(0,2).map(([k,v])=>`${k} ${fmtPct(v)}`).join(' · ')||'N/A'}</b><small>${Object.entries(perf).slice(2).map(([k,v])=>`${k} ${fmtPct(v)}`).join(' · ')}</small></div></div></section>
 <section class="ex-card full"><h3>INTERACTIVE PRICE RESEARCH <span class="hint">REPORTED BARS + CALCULATED INDICATORS</span></h3><div class="chart-tools" id="rangeTools"><button data-range="1m" data-interval="1d" class="on">1M · DAILY</button><button data-range="3m" data-interval="1d">3M · DAILY</button><button data-range="6m" data-interval="1d">6M · DAILY</button><button data-range="1y" data-interval="1d">1Y · DAILY</button><button data-range="2y" data-interval="1w">2Y · WEEKLY</button><button data-range="10d" data-interval="15m">10D · 15M</button></div><div class="chart-tools" id="chartTools"><button data-chart="sma20" class="on">SMA 20</button><button data-chart="sma50">SMA 50</button><button data-chart="vwap" class="on">VWAP</button><button data-chart="rsi">RSI 14</button><button data-chart="macd">MACD</button><button data-chart="atr">ATR 14</button><button id="compareSPY">COMPARE SPY</button><button id="compareSector">SECTOR ${esc(sectorETF(p.sector)||'ETF')}</button><button id="comparePeer">＋ PEER</button></div><canvas class="research-chart" id="researchChart"></canvas><div class="chart-legend" id="researchChartLegend"></div><div id="technicalSummary" style="margin-top:10px">${renderTechnicalSummary(b.bars||[])}</div><div class="chart-help">Candles and volume are <b>MARKET DATA</b>. Moving averages, RSI, MACD, ATR, support/resistance and relative comparison overlays are <b>MODEL CALCULATIONS</b>. Cached bars use the provider’s adjusted convention. Intraday/weekly views require the connected research API when they are not in cache.</div></section>
 ${isETF?renderFund(b):renderFundamentals(b)}
 <section class="ex-card wide"><h3>NEWS / FILINGS / CATALYST TIMELINE</h3><input class="timeline-search" id="timelineSearch" placeholder="Filter timeline…"><div id="timelineRows">${renderTimelineRows(b.news||[])}</div></section>
 <section class="ex-card"><h3>EARNINGS / CATALYSTS</h3><div id="earningsPanel">${renderEarnings(b.earnings)}</div></section>
 <section class="ex-card"><h3>ANALYST RESEARCH</h3><div id="analystPanel">${renderAnalyst(b.analyst)}</div></section>
 <section class="ex-card"><h3>OWNERSHIP / POSITIONING</h3><div id="positioningPanel">${renderPositioning(b.positioning)}</div></section>
 <section class="ex-card"><h3>OPTIONS</h3><div id="optionsPanel">${renderOptions(b.options)}</div></section>
 <section class="ex-card full recovery-assess"><h3>RECOVERY OS ASSESSMENT</h3>${renderRecoveryAssessment(b,tr)}<button class="queue-btn" id="queueRecovery">${tr?'OPEN CANONICAL RECOVERY ROOM':'SUBMIT TO RECOVERY RESEARCH QUEUE'}</button></section>
 <section class="ex-card half"><h3>RESEARCH NOTES</h3><textarea class="note-area" id="researchNote" placeholder="Your research notes for ${esc(t)}…">${esc(user.notes[t]||'')}</textarea><div class="source-note">Stored separately from the recovery tracker. Local device persistence in cached mode.</div></section>
 <section class="ex-card half"><h3>DATA PROVENANCE / LIMITS</h3>${renderProvenance(b)}</section>
 </div>`;
 qs('#stockContent').innerHTML=html;renderStockActions();bindStock(t,b,tr);}
