function renderExplore(){const recent=user.recent, fav=user.favorites;qs('#recentSearches').innerHTML=recent.length?recent.map(symbolCard).join(''):'<div class="empty-panel">Your recent searches will appear here.</div>';qs('#favoriteStocks').innerHTML=fav.length?fav.map(symbolCard).join(''):'<div class="empty-panel">Favorite any research page to build a quick-access list.</div>';bindSymbolCards(qs('#ex-explore'))}
function symbolCard(t){const s=getSym(t);return `<div class="symbol-card" data-open-symbol="${esc(t)}"><div class="row"><b>${esc(t)}</b><button class="favorite-star ${user.favorites.includes(t)?'on':''}" data-favorite-symbol="${esc(t)}">★</button></div><small>${esc(s.name)}<br>${esc(s.exchange)} · ${esc(s.securityType)}</small></div>`}
function bindSymbolCards(root=document){qsa('[data-open-symbol]',root).forEach(x=>x.onclick=e=>{if(e.target.closest('[data-favorite-symbol]'))return;openResearch(x.dataset.openSymbol)});qsa('[data-favorite-symbol]',root).forEach(x=>x.onclick=e=>{e.stopPropagation();toggleFavorite(x.dataset.favoriteSymbol);renderExplore()})}
function sampleUniverse(){const arr=[];if(SEED?.stocks?.AAPL){const a=SEED.stocks.AAPL;arr.push({ticker:'AAPL',name:a.profile.name,type:a.profile.securityType,sector:a.profile.sector,price:a.quote.price,marketCap:a.profile.marketCap,drawdown:Math.abs(a.quote.from52wHighPct),perf1m:a.quote.performancePct['1M'],avgVolume:a.quote.avgVolume20,recovery:'NO'})}const r=recoveryState();(r?.stocks||[]).forEach(x=>arr.push({ticker:x.ticker,name:x.company,type:'Common Stock',sector:x.sector||'—',price:x.latestPrice,marketCap:null,drawdown:null,perf1m:null,avgVolume:null,recovery:x.universeClass==='QUALIFIED'?'QUALIFIED':'PROVISIONAL'}));return arr}
function renderScreenCriteria(){
 const v=qs('#starterScreen')?.value||'custom',m={custom:'CUSTOM · Price, market cap, average volume, valuation, profitability and leverage filters are sent only when supported.',earnings:'APPROACHING EARNINGS · Requires the optional earnings calendar; ratios alone cannot provide a legitimate earnings-window screen.',profitability:'IMPROVING PROFITABILITY · Uses positive ROE as an entitled financial prefilter; trend improvement still requires consistent fiscal-period comparison.',recovery:'RECOVERY CANDIDATES · Financial/liquidity prefilter only in the generic screener. Full Recovery OS drawdown + crisis + survival + catalyst + stabilization rules remain separate and never auto-qualify.'};if(qs('#starterCriteria'))qs('#starterCriteria').innerHTML='<b>'+v.toUpperCase()+'</b> · '+m[v]
}
function renderScreener(){
 renderScreenCriteria();const universe=sampleUniverse(),minPrice=Number(qs('#screenMinPrice')?.value||0),recoveryOnly=qs('#screenRecovery')?.value||'ALL';
 const rows=universe.filter(x=>x.price==null||x.price>=minPrice).filter(x=>recoveryOnly==='ALL'||x.recovery===recoveryOnly);
 qs('#screenerCoverage').innerHTML=apiBase()?`<b>CONNECTED MODE</b> · Full-universe queries use the entitled provider dataset. Current table remains the local sample until RUN SCREEN is pressed.`:`<b>CACHED MODE</b> · LOCAL SAMPLE ONLY (${universe.length} records). This is not a market-wide screen. Connect the research API for the provider universe.`;
 qs('#screenerRows').innerHTML=rows.map(x=>`<tr data-open-symbol="${x.ticker}"><td><b>${x.ticker}</b><br>${esc(x.name)}</td><td>${esc(x.type)}</td><td>${fmtMoney(x.price)}</td><td>${fmtMoney(x.marketCap,true)}</td><td>${x.drawdown==null?'N/A':fmtPct(-x.drawdown)}</td><td>${fmtPct(x.perf1m)}</td><td>${fmtNum(x.avgVolume,0)}</td><td>${x.pe==null?'N/A':fmtNum(x.pe,1)}</td><td>${x.roe==null?'N/A':fmtPct(x.roe,1)}</td><td>${x.debtToEquity==null?'N/A':fmtNum(x.debtToEquity,2)}</td><td>${esc(x.recovery)}</td></tr>`).join('')||'<tr><td colspan="11">No sample rows match.</td></tr>';bindSymbolCards(qs('#ex-screener'))
}
