async function searchSymbols(q){
 q=q.trim();if(!q)return[];
 const clean=q.toUpperCase().replace(/[^A-Z0-9.\-]/g,'');
 let local=SYMBOLS.filter(x=>x.ticker.toLowerCase().includes(q.toLowerCase())||x.name.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>(a.ticker.toLowerCase()===q.toLowerCase()?-1:0)-(b.ticker.toLowerCase()===q.toLowerCase()?-1:0)).slice(0,8).map(x=>({...x,supported:true}));
 if(apiBase()&&q.length>=1){try{const r=await api('/api/search?q='+encodeURIComponent(q));const remote=(r.results||[]).map(x=>({ticker:x.ticker,name:x.name,exchange:x.exchange||x.primary_exchange||'—',securityType:x.type||x.securityType||'—',supported:x.supported!==false,unsupportedReason:x.unsupportedReason||null,remote:true}));const seen=new Set();local=[...remote,...local].filter(x=>!seen.has(x.ticker)&&(seen.add(x.ticker),true)).slice(0,12)}catch(e){console.warn('remote search',e)}}
 if(!local.length&&/^[A-Z0-9.\-]{1,12}$/.test(clean))local=[{ticker:clean,name:'Uncached symbol — research shell',exchange:'VERIFY VIA SEC / CONNECTED SOURCE',securityType:'Stock / ADR / ETF to verify',supported:true,freeShell:true}];
 return local
}
function mountSuggest(input,box){input.addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(async()=>renderSuggest(input,box),140)});input.addEventListener('focus',()=>{if(input.value.trim())renderSuggest(input,box)});input.addEventListener('keydown',e=>{if(e.key==='Enter'){const first=box.querySelector('[data-search-ticker]');if(first){e.preventDefault();openResearch(first.dataset.searchTicker)}else if(input.value.trim())openResearch(input.value.trim().toUpperCase())}if(e.key==='Escape')box.classList.remove('show')})}
async function renderSuggest(input,box){
 const q=input.value.trim();if(!q){box.classList.remove('show');return}
 box.innerHTML='<div class="search-empty">Resolving symbol…</div>';box.classList.add('show');const rows=await searchSymbols(q);
 if(!rows.length){box.innerHTML=`<div class="search-empty"><b>No valid ticker match</b><br>Use a U.S. ticker such as PLTR, AAPL, SPY, NKE or BRK.B.</div><div class="search-source">FREE HYBRID MODE · NO PAID DATA REQUIRED</div>`;return}
 box.innerHTML=rows.map(x=>`<div class="search-item ${x.supported===false?'unsupported':''}" data-search-ticker="${esc(x.ticker)}" data-supported="${x.supported===false?'false':'true'}"><b>${esc(x.ticker)}</b><span>${esc(x.name)}<br>${esc(x.exchange)}</span><em>${esc(x.securityType)}${x.supported===false?' · UNSUPPORTED':''}</em></div>`).join('')+`<div class="search-source">${apiBase()?'CONNECTED RESEARCH + LOCAL RESULTS':'FREE HYBRID RESEARCH · CACHED DATA WHEN AVAILABLE · SEC/TRADINGVIEW BRIDGE READY'}</div>`;
 box.querySelectorAll('[data-search-ticker]').forEach(el=>el.onclick=()=>{box.classList.remove('show');input.value='';if(el.dataset.supported==='false'){openExplorer('stock');renderError('UNSUPPORTED SECURITY',rows.find(x=>x.ticker===el.dataset.searchTicker)?.unsupportedReason||'This security type is outside the current Stock Explorer coverage.');return}openResearch(el.dataset.searchTicker)})
}
async function fetchBundle(t){t=t.toUpperCase();if(apiBase()){try{const r=await api('/api/stock/'+encodeURIComponent(t));return r.stock||r}catch(e){if(seedBundle(t)){toastEx('Remote research unavailable · showing cached data');return seedBundle(t)}throw e}}return seedBundle(t)}
function freeResearchShell(t,s){return{profile:{ticker:t,name:s?.name||t,exchange:s?.exchange||'TO VERIFY',securityType:s?.securityType||'COMMON STOCK / ADR / ETF — TO VERIFY'},quote:null,bars:[],news:[],financials:{quarterly:[],annual:[]},whatMatters:[{type:'LIMITATION',text:'No paid market-data feed is connected. Recovery OS opened this ticker instead of blocking it.'},{type:'FACT',text:'SEC EDGAR public company/filing data can be attached without a paid API key once the free server-side bridge is enabled.'},{type:'MARKET DATA',text:'Use TradingView for live chart/quote context. TradingView subscription data is not treated as a general-purpose API feed.'},{type:'INTERPRETATION',text:'Recovery OS will calculate technical indicators locally whenever OHLCV bars are available.'}],recoveryAssessment:{tracked:false,headline:'GENERAL RESEARCH ONLY — NOT QUALIFIED',classification:'FREE RESEARCH SHELL — FORMAL RECOVERY REVIEW REQUIRED'},dataState:{mode:'FREE HYBRID',price:'UNAVAILABLE UNTIL FREE BAR SOURCE / TRADINGVIEW EVENT',filings:'SEC BRIDGE READY',technicals:'CALCULATED WHEN BARS AVAILABLE'}}}
async function openResearch(t){t=t.trim().toUpperCase();const isNew=t!==currentTicker;if(isNew)viewScroll.stock=0;if(!/^[A-Z0-9.\-]{1,12}$/.test(t)){openExplorer('stock');renderError('INVALID SYMBOL','Use a valid ticker such as PLTR, AAPL, SPY, NKE or BRK.B.');return}openExplorer('stock');currentTicker=t;history.replaceState(null,'',`#research/${encodeURIComponent(t)}`);qs('#stockContent').innerHTML='<div class="empty-panel"><strong>LOADING RESEARCH</strong>Resolving cached evidence, tracker status and free-data coverage…</div>';try{let b=await fetchBundle(t);if(!b){const s=SYMBOLS.find(x=>x.ticker===t);b=freeResearchShell(t,s)}currentBundle=b;addRecent(t);renderStock(b);requestAnimationFrame(()=>{const m=qs('.ex-main');if(m)m.scrollTop=viewScroll.stock||0});}catch(e){const s=SYMBOLS.find(x=>x.ticker===t);const b=freeResearchShell(t,s);currentBundle=b;addRecent(t);renderStock(b);toastEx('Paid/remote research unavailable · opened free research shell')}}
function renderError(title,text){qs('#stockContent').innerHTML=`<div class="ex-page-head"><div><h2>${esc(currentTicker||'STOCK RESEARCH')}</h2><p>Recovery OS Stock Explorer</p></div></div><div class="empty-panel"><strong>${esc(title)}</strong>${esc(text)}<br><br><button class="ex-btn" data-back-explore>SEARCH ANOTHER STOCK</button></div>`;qs('[data-back-explore]')?.addEventListener('click',()=>showView('explore'))}
function sectorETF(sector){return ({'Information Technology':'XLK','Financials':'XLF','Energy':'XLE','Health Care':'XLV','Consumer Discretionary':'XLY','Consumer Staples':'XLP','Industrials':'XLI','Materials':'XLB','Utilities':'XLU','Real Estate':'XLRE','Communication Services':'XLC'}[sector]||null)}
function techStats(bars){if(!bars?.length)return null;const z=bars.at(-1),last20=bars.slice(-20),support=Math.min(...last20.map(x=>x.low)),resistance=Math.max(...last20.map(x=>x.high));let peak=-Infinity,maxDD=0;for(const x of bars){peak=Math.max(peak,x.high);maxDD=Math.min(maxDD,(x.low/peak-1)*100)}const gaps=[];for(let i=1;i<bars.length;i++){const g=(bars[i].open/bars[i-1].close-1)*100;if(Math.abs(g)>=1)gaps.push({date:bars[i].date,pct:g})}const closes=bars.map(x=>x.close),s20=window.RecoveryIndicators?.sma(closes,20).at(-1),atr14=window.RecoveryIndicators?.atr(bars,14).at(-1);return{support,resistance,maxDD,s20,atr14,gap:gaps.sort((a,b)=>Math.abs(b.pct)-Math.abs(a.pct))[0]||null,trend:s20==null?'UNKNOWN':z.close>s20?'ABOVE SMA20':'BELOW SMA20'}}
function renderTechnicalSummary(bars){const x=techStats(bars);if(!x)return'<div class="empty-panel">Technical calculations require OHLCV bars. Live chart context can remain in TradingView; Recovery OS will calculate indicators when a free bar source or TradingView event supplies data.</div>';return `<div class="metric-grid"><div class="stat"><label>20-Bar Support</label><b>${fmtMoney(x.support)}</b><small>MODEL CALCULATION</small></div><div class="stat"><label>20-Bar Resistance</label><b>${fmtMoney(x.resistance)}</b><small>MODEL CALCULATION</small></div><div class="stat"><label>ATR 14 ⓘ</label><b title="${esc(DEFINITIONS['ATR'])}">${fmtMoney(x.atr14)}</b></div><div class="stat"><label>Structure</label><b>${esc(x.trend)}</b><small>INTERPRETATION</small></div><div class="stat"><label>Sample Max Drawdown</label><b>${fmtPct(x.maxDD)}</b><small>FROM LOADED BARS</small></div><div class="stat"><label>Largest ≥1% Gap</label><b>${x.gap?fmtPct(x.gap.pct):'NONE'}</b><small>${x.gap?.date||'IN LOADED SAMPLE'}</small></div></div>`}
