/* Device-local, append-only research history. No canonical tracker mutations. */
(()=>{'use strict';const F=window.RecoveryInformation,DB_NAME='recovery-information-v1';let dbPromise,queue=Promise.resolve();const memory=new Map();const api={status:'Opening research history',persistent:false,current:new Map(),priorVisits:new Map(),audit:[],preferences:{enabled:true,performance:'auto',color:'sector',size:'marketCap',height:'strength',period:'1D',relationships:false},recent:[],locations:[]};
// Research record identifiers also work in an HTTP/offline review build. These are not security tokens.
let sequence=0;const uuid=()=>globalThis.crypto?.randomUUID?.()||F.id([Date.now(),performance.now(),++sequence,Math.random()]);
const open=()=>dbPromise||(dbPromise=new Promise((resolve,reject)=>{if(!window.indexedDB)return reject(new Error('IndexedDB unavailable'));const req=indexedDB.open(DB_NAME,2);req.onupgradeneeded=()=>{for(const name of ['snapshots','changes','visits','annotations','settings','audits','events'])if(!req.result.objectStoreNames.contains(name))req.result.createObjectStore(name,{keyPath:'id'})};req.onsuccess=()=>{api.persistent=true;api.status='Research history saved on this device';resolve(req.result)};req.onerror=()=>reject(req.error)}).catch(()=>{api.status='Session-only history: this browser could not open persistent storage. Export before closing.';return null}));
async function all(name){const db=await open();if(!db)return[...(memory.get(name)||new Map()).values()];return new Promise((res,rej)=>{const req=db.transaction(name).objectStore(name).getAll();req.onsuccess=()=>res(req.result);req.onerror=()=>rej(req.error)})}
async function write(name,value,append=false){const db=await open();if(!db){if(!memory.has(name))memory.set(name,new Map());if(!append||!memory.get(name).has(value.id))memory.get(name).set(value.id,F.clone(value));return}return new Promise((res,rej)=>{const tx=db.transaction(name,'readwrite'),store=tx.objectStore(name);if(append){const req=store.get(value.id);req.onsuccess=()=>{if(!req.result)store.add(value)}}else store.put(value);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
api.ready=(async()=>{const settings=await all('settings');const prefs=settings.find(x=>x.id==='preferences');if(prefs)Object.assign(api.preferences,prefs.value);api.recent=settings.find(x=>x.id==='recent')?.value||[];api.locations=settings.find(x=>x.id==='locations')?.value||[];return api})();
api.log=async(type,detail)=>{const record={id:uuid(),at:new Date().toISOString(),type,detail};api.audit.push(record);await write('audits',record,true);return record};
api.observe=(d,{visit=false}={})=>{const task=queue.then(async()=>{await api.ready;const identity=d.identity.securityId,old=(await api.history()).filter(s=>s.identity.securityId===identity).sort((a,b)=>a.observedAt.localeCompare(b.observedAt)),before=old.at(-1)||null;const visits=(await all('visits')).filter(s=>s.securityId===identity).sort((a,b)=>a.at.localeCompare(b.at));if(visit)api.priorVisits.set(identity,visits.at(-1)||null);d.events=[...new Map([...d.events,...old.flatMap(s=>s.events)].map(e=>[e.id,e])).values()].sort((a,b)=>String(a.publishedAt).localeCompare(String(b.publishedAt)));let snap=F.snapshot(d);const changed=!before||F.signature(before)!==F.signature(snap);if(!changed)snap=before;const changes=changed?F.changes(before,snap):[];if(changed){for(const e of snap.events)await write('events',e,true);const {events,...rest}=snap;await write('snapshots',{...rest,eventIds:events.map(e=>e.id)},true);}for(const c of changes)await write('changes',c,true);if(visit){await write('visits',{id:uuid(),securityId:identity,ticker:d.identity.ticker,at:d.observedAt,snapshotId:snap.id},true);if(api.preferences.enabled){api.recent=[d.identity.ticker,...api.recent.filter(x=>x!==d.identity.ticker)].slice(0,20);await write('settings',{id:'recent',value:api.recent})}}api.current.set(d.identity.ticker,d);return{snapshot:snap,previous:before,changes,previousVisit:api.priorVisits.get(identity)||null}});queue=task.catch(e=>{api.status='History save failed: export this session before closing.';console.warn('Research history unavailable',e.name)});return task};
api.history=async ticker=>{const events=new Map((await all('events')).map(e=>[e.id,e]));return(await all('snapshots')).filter(s=>!ticker||s.identity.ticker===ticker).map(s=>({...s,events:s.events||s.eventIds.map(id=>events.get(id)).filter(Boolean)})).sort((a,b)=>a.observedAt.localeCompare(b.observedAt))};
api.changes=async ticker=>(await all('changes')).filter(c=>!ticker||c.ticker===ticker).sort((a,b)=>b.detectedAt.localeCompare(a.detectedAt));
api.annotations=()=>all('annotations');api.annotate=(id,patch)=>{const task=queue.then(async()=>{const previous=(await all('annotations')).find(x=>x.id===id)||{};await write('annotations',{...previous,...patch,id,at:new Date().toISOString()})});queue=task.catch(()=>{api.status='Annotation save failed; export before closing.'});return task};
api.setPreferences=async patch=>{const previous={...api.preferences};Object.assign(api.preferences,patch);await write('settings',{id:'preferences',value:api.preferences});await api.log('PREFERENCES',{before:previous,after:api.preferences});window.dispatchEvent(new CustomEvent('information-preferences',{detail:api.preferences}))};
api.saveLocation=async(value)=>{api.locations=[{id:uuid(),...value,at:new Date().toISOString()},...api.locations].slice(0,20);await write('settings',{id:'locations',value:api.locations})};
api.resetPersonalization=async()=>{const before={preferences:api.preferences,recent:api.recent,locations:api.locations};api.recent=[];api.locations=[];await write('settings',{id:'recent',value:[]});await write('settings',{id:'locations',value:[]});await api.setPreferences({enabled:false,color:'sector',size:'marketCap',height:'strength',period:'1D',performance:'auto',relationships:false});await api.log('PERSONALIZATION_RESET',{before,restorable:true})};
api.export=async()=>Object.fromEntries(await Promise.all(['snapshots','events','changes','visits','annotations','settings','audits'].map(async k=>[k,await all(k)])));
const serverSync=new Map();
api.syncServer=async ticker=>{if(!ticker||!apiBase())return;if(serverSync.has(ticker)&&Date.now()-serverSync.get(ticker)<300000)return;serverSync.set(ticker,Date.now());try{
 const results=await Promise.all([window.api('/api/information/snapshots/'+encodeURIComponent(ticker)),window.api('/api/information/changes/'+encodeURIComponent(ticker))]);
 const securityId=api.current.get(ticker)?.identity.securityId;
 const task=queue.then(async()=>{for(const s of results[0].records||[]){if(s.schemaVersion!==F.VERSION||s.identity?.securityId!==securityId||s.identity?.ticker!==ticker||!F.iso(s.observedAt))continue;for(const e of s.events||[])await write('events',e,true);const {events,...rest}=s;await write('snapshots',{...rest,eventIds:(events||[]).map(e=>e.id)},true)}for(const c of results[1].records||[])if(c.securityId===securityId&&c.ticker===ticker&&F.iso(c.detectedAt))await write('changes',c,true)});queue=task.catch(()=>{});await task;
}catch{await api.log('HISTORY_SYNC_UNAVAILABLE',{ticker,reason:'Retained device history; configured server history could not be read.'})}};
api.all=all;window.RecoveryHistory=api;
})();
