import * as THREE from './vendor/three.module.min.js';
import {StockUniverse} from './research-universe.js';
import {installInformationWorld} from './information-world.js';
import {HologramRenderer} from './world-renderer.js';

const el=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)],mobile=()=>innerWidth<760;
const SECTORS=[['Technology','Technology',0x69d9ee],['Health Care','Health care',0xa895ef],['Finance','Finance',0x7baced],['Consumer Discretionary','Consumer',0xf1bb89],['Consumer Staples','Staples',0xb8cf8c],['Industrials','Industrials',0x87cbbc],['Energy','Energy',0xeac279],['Basic Materials','Materials',0xc99f86],['Telecommunications','Communications',0x9dacf1],['Utilities','Utilities',0x96c4e0],['Real Estate','Real estate',0xa7bad6],['Funds','Funds & indices',0xcbdcb9],['Market frontier','Market frontier',0x7b90af]];
const STATIONS=[['sectors','Sector atlas','Every industry. Every connection.',0x91d6ea],['tracker','Recovery lab','Theses, confirmation and history.',0xb5a5f3],['news','News observatory','Follow the next development.',0xefc690],['macro','Macro sphere','Rates, inflation and policy.',0x89d3ba],['workspace','Your workspace','Saved companies, notes and comparisons.',0xa7c6f0],['sources','Source archive','The public evidence behind the world.',0xa1bbcc]];
const ROOT_OPEN=openExplorer,ROOT_VIEW=showView,ROOT_RESEARCH=openResearch,ROOT_RENDER=renderResearchWorld,ROOT_SELECT=selectResearchSection,ROOT_READER=renderResearchReader;
let market=null,routeBusy=false;
const symbolKey=t=>{const value=String(t||'').toUpperCase();if(ATLAS_SYMBOLS.has(value))return value;const dashed=value.replace(/\./g,'-');return ATLAS_SYMBOLS.has(dashed)?dashed:value};
function currentState(){return typeof STATE==='object'&&STATE?STATE:recoveryState()}
function trackedWorldPrice(r){const x=tracked(r.ticker);return MODEL.finite(x?.latestPrice)?x.latestPrice:r.price}
function trackedWorldChange(r){const x=tracked(r.ticker),s=x?.priceSeries||[];if(s.length>1&&MODEL.finite(s.at(-1)?.close)&&MODEL.finite(s.at(-2)?.close)&&s.at(-2).close!==0)return(s.at(-1).close/s.at(-2).close-1)*100;return r.changePct}
function sectorKey(r){if(/ETF/i.test(r.securityType||''))return'Funds';return SECTORS.some(s=>s[0]===r.sector)?r.sector:'Market frontier'}
function hashText(t){let x=2166136261;for(const c of t)x=Math.imul(x^c.charCodeAt(0),16777619)>>>0;return x}
function navRoute(hash){if(location.hash!==hash)history.pushState(null,'',hash)}

class MarketWorld extends StockUniverse{
  mount(){
    super.mount();
    const ex=el('#explorer');ex.setAttribute('role','main');ex.removeAttribute('aria-modal');
    el('.ex-title b').textContent='RECOVERY // OS';el('.ex-title small').textContent='THE OPEN MARKET ATLAS';el('#closeExplorer').setAttribute('aria-label','Return to the market universe');el('#researchSettingsBtn').setAttribute('aria-label','Data sources and coverage');
    el('.universe-eyebrow').innerHTML='<span class="universe-live-dot"></span> THE OPEN MARKET ATLAS';
    el('.universe-footer>div').innerHTML='<button id="atlasHome">◉ <span>Universe</span></button><button id="atlasSectors">⌘ <span>Sectors</span></button><button id="universeTracker">◇ <span>Recovery</span></button><button id="atlasNews">◈ <span>News</span></button><button id="atlasMacro">◎ <span>Macro</span></button><button id="atlasWorkspace">▣ <span>Workspace</span></button><span hidden><button id="universeReader">Reading view</button><button id="universeCompare">Compare</button><button id="universeNotes">Notes</button></span>';
    el('#universeRefresh').setAttribute('title','Refresh the current evidence');
    const station=document.createElement('section');station.className='ex-view';station.id='ex-atlas';el('.ex-main').append(station);
    const tape=document.createElement('div');tape.id='atlasTape';tape.setAttribute('aria-label','Market snapshot highlights');el('#universeHUD').append(tape);
    const tools=document.createElement('div');tools.id='atlasStockTools';tools.innerHTML='<button id="atlasSave">☆ Save company</button><button id="atlasCompare">Compare ↗</button><button id="atlasNote">Notes ↗</button>';el('#universeHUD').append(tools);
    const locator=document.createElement('div');locator.id='atlasLocation';locator.innerHTML='<span>YOU ARE EXPLORING</span><b>THE MARKET UNIVERSE</b>';el('#universeHUD').append(locator);
  }
  initScene(){
    this.registry=(ATLAS_INDEX.length?ATLAS_INDEX:OPEN_RESEARCH_INDEX).map((r,i)=>({...r,sector:sectorKey(r),seed:hashText(r.ticker),index:i}));
    this.sectors=SECTORS.map(([id,title,color],i)=>({id,title,color,kind:'sector',base:new THREE.Vector3(Math.sin(i/SECTORS.length*Math.PI*2)*1080,0,Math.cos(i/SECTORS.length*Math.PI*2)*1080)}));
    for(const r of this.registry){const center=this.sectors.find(s=>s.id===r.sector),angle=(r.seed%10000)/10000*Math.PI*2,radius=45+Math.sqrt((r.seed>>>12)%1000)/31.63*300;r.position=center.base.clone().add(new THREE.Vector3(Math.sin(angle)*radius,0,Math.cos(angle)*radius));}
    this.registryMap=new Map(this.registry.map(r=>[r.ticker,r]));this.stationNodes=[];this.sectorNodes=[];this.lastPool=0;this.focusDistrict=null;
    super.initScene();this.camera.far=40000;this.camera.updateProjectionMatrix();this.scene.fog.density=.00055;this.canvas.dataset.renderer=this.renderer.software?'perspective-canvas':'webgl';
    this.addDistricts();this.addStations();this.addPlanet();this.refreshTape();
    this.records=OPEN_RESEARCH_INDEX;this.renderer.setPixelRatio(Math.min(devicePixelRatio,this.renderer.software?1.2:mobile()?1.4:1.8));
  }
  addCompanyHubs(){
    const vertices=[],colors=[];for(const r of this.registry){vertices.push(r.position.x,r.position.y,r.position.z);const color=new THREE.Color(this.sectors.find(x=>x.id===r.sector).color);colors.push(color.r,color.g,color.b)}
    const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));geometry.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));const cloud=new THREE.Points(geometry,new THREE.PointsMaterial({size:2.1,vertexColors:true,transparent:true,opacity:.72}));cloud.userData.marketCloud=true;this.scene.add(cloud);
    this.pool=[];const baseGeometry=new THREE.CylinderGeometry(8,12,2,6),towerGeometry=new THREE.BoxGeometry(3,1,3),beaconGeometry=new THREE.OctahedronGeometry(2.5,0);
    for(let i=0;i<(mobile()?24:46);i++){
      const group=new THREE.Group();const base=new THREE.Mesh(baseGeometry,this.material(0x1d425c,.72));base.position.y=-4;group.add(base);group.add(this.ring(13,0x7abdd6,-3));const towers=[];for(let n=0;n<3;n++){const tower=new THREE.Mesh(towerGeometry,this.material(0x639eb7,.6));tower.position.x=(n-1)*5;group.add(tower);towers.push(tower)}const beacon=new THREE.Mesh(beaconGeometry,this.material(0x9fdff1));beacon.position.y=24;group.add(beacon);this.scene.add(group);
      const node={id:'',title:'',kind:'company',kicker:'COMPANY',detail:'',position:new THREE.Vector3(),base:new THREE.Vector3(),group,beacon,towers};base.userData.node=node;beacon.userData.node=node;this.pickables.push(base,beacon);this.pool.push(this.addLabel(node));
    }
    this.hubs=this.pool;
  }
  addLabel(node){
    const button=document.createElement('button');button.className='universe-node-label '+node.kind;button.type='button';button.hidden=true;button.innerHTML='<small></small><strong></strong><em></em>';this.labelHost.append(button);node.label=button;this.labels.push(node);button.onclick=()=>{this.stopTour();if(node.kind==='company'){if(window.RecoveryWorldInfo)window.RecoveryWorldInfo.select(node.id);else openResearch(node.id)}else if(node.kind==='sector')this.district(node.id);else if(node.kind==='station')this.station(node.id);else selectResearchSection(node.id,{scroll:false})};this.label(node);return node;
  }
  label(node){const b=node.label;b.dataset.universeNode=node.id;b.querySelector('small').textContent=node.kicker||'';b.querySelector('strong').textContent=node.title+' ↗';b.querySelector('em').textContent=node.detail||'';b.setAttribute('aria-label','Explore '+(node.title||'company'))}
  addDistricts(){
    for(const sector of this.sectors){const group=new THREE.Group();group.position.copy(sector.base);group.add(this.ring(355,sector.color,-16));group.add(this.ring(345,sector.color,-16));const beacon=new THREE.Mesh(new THREE.OctahedronGeometry(16,0),this.material(sector.color,.38));beacon.position.y=100;group.add(beacon);const halo=this.glow(sector.color,120);halo.position.y=96;group.add(halo);this.scene.add(group);const count=this.registry.filter(r=>r.sector===sector.id).length;const node={...sector,group,beacon,kicker:'SECTOR DISTRICT',detail:count.toLocaleString()+' securities',position:sector.base.clone().setY(128)};beacon.userData.node=node;this.pickables.push(beacon);this.sectorNodes.push(this.addLabel(node));}
  }
  addStations(){
    STATIONS.forEach(([id,title,detail,color],i)=>{const angle=i/STATIONS.length*Math.PI*2+.38,pos=new THREE.Vector3(Math.sin(angle)*265,0,Math.cos(angle)*265),group=new THREE.Group();group.position.copy(pos);group.add(this.ring(30,color,-8));group.add(this.ring(38,color,-8));const mesh=new THREE.Mesh(i%2?new THREE.IcosahedronGeometry(17,0):new THREE.BoxGeometry(27,35,8),this.material(color,.56));mesh.position.y=23;group.add(mesh);const halo=this.glow(color,88);halo.position.y=26;group.add(halo);this.scene.add(group);const node={id,title,detail,color,kind:'station',kicker:'0'+(i+1)+' / WORLD DESTINATION',base:pos,position:pos.clone().setY(60),group,beacon:mesh};mesh.userData.node=node;this.pickables.push(mesh);this.stationNodes.push(this.addLabel(node));this.scene.add(this.line([new THREE.Vector3(0,-8,0),pos.clone().setY(-8)],color,.16))});
  }
  addPlanet(){
    this.planet=new THREE.Group();this.planet.position.set(0,80,0);this.scene.add(this.planet);
    for(let lat=-3;lat<=3;lat++){const angle=lat*Math.PI/8,r=Math.cos(angle)*80,points=[];for(let i=0;i<=72;i++){const t=i/72*Math.PI*2;points.push(new THREE.Vector3(Math.cos(t)*r,Math.sin(angle)*80,Math.sin(t)*r))}this.planet.add(this.line(points,0x76c6dc,.2))}
    for(let lng=0;lng<12;lng++){const points=[];for(let i=0;i<=64;i++){const a=i/64*Math.PI*2;points.push(new THREE.Vector3(Math.cos(a)*Math.cos(lng*Math.PI/6)*80,Math.sin(a)*80,Math.cos(a)*Math.sin(lng*Math.PI/6)*80))}this.planet.add(this.line(points,0x76c6dc,.22))}
    const orbit=this.ring(107,0x99dfe8);orbit.rotation.z=.35;this.planet.add(orbit);const orbit2=this.ring(120,0x729bc7);orbit2.rotation.x=.75;this.planet.add(orbit2);const halo=this.glow(0x215f87,260);this.planet.add(halo);
    const sats=[];for(let i=0;i<80;i++){const z=1-2*(i+.5)/80,a=i*2.399963,r=Math.sqrt(1-z*z);sats.push(r*Math.cos(a)*81,z*81,r*Math.sin(a)*81)}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(sats,3));this.planet.add(new THREE.Points(geo,new THREE.PointsMaterial({color:0xa5eff0,size:2.5,transparent:true,opacity:.9})));
  }
  refreshPool(force=false){
    if(!force&&performance.now()-this.lastPool<700)return;this.lastPool=performance.now();const target=this.cameraTarget||new THREE.Vector3();let records=this.focusDistrict?this.registry.filter(r=>r.sector===this.focusDistrict):this.registry;
    if(window.RecoveryWorldInfo?.matches)records=records.filter(window.RecoveryWorldInfo.matches);
    if(this.locationKind==='home')records=[...records].sort((a,b)=>(b.marketCap||0)-(a.marketCap||0)).slice(0,this.pool.length);
    else records=[...records].sort((a,b)=>a.position.distanceToSquared(target)-b.position.distanceToSquared(target)).slice(0,this.pool.length);
    if(this.selected){const selected=this.registryMap.get(this.selected);if(selected&&!records.includes(selected))records[records.length-1]=selected}
    this.pool.forEach((node,i)=>{const r=records[i];node.group.visible=!!r;if(!r){node.id='';return}node.id=r.ticker;node.title=r.ticker;node.kicker=r.sector;const shownPrice=trackedWorldPrice(r),shownChange=trackedWorldChange(r);node.detail=MODEL.finite(shownPrice)?fmtMoney(shownPrice)+(MODEL.finite(shownChange)?' · '+fmtPct(shownChange,2):''):r.name;node.position.copy(r.position).add(new THREE.Vector3(0,31,0));node.base.copy(r.position);node.group.position.copy(r.position);node.towers.forEach((tower,j)=>{const height=10;tower.scale.y=height;tower.position.y=height/2});this.label(node)});
  }
  bind(){
    super.bind();
    el('#atlasHome').onclick=()=>this.home();el('#atlasSectors').onclick=()=>this.station('sectors');el('#universeTracker').onclick=()=>this.station('tracker');el('#atlasNews').onclick=()=>this.station('news');el('#atlasMacro').onclick=()=>this.station('macro');el('#atlasWorkspace').onclick=()=>this.station('workspace');
    el('#universeGeneral').onclick=()=>this.selected?selectResearchSection('brief',{scroll:false}):this.station('sectors');el('#universeOverview').onclick=()=>this.home();el('#universeTour').onclick=()=>this.startTour();el('#universeExpand').onclick=()=>this.reading(!document.body.classList.contains('atlas-reading'));el('#returnUniverse').onclick=()=>this.reading(false);el('#universeReader').onclick=()=>this.reading(true);el('#universePaneClose').onclick=()=>this.closePane();el('#closeExplorer').onclick=()=>this.home();el('#researchSettingsBtn').onclick=()=>this.station('sources');el('#universeRefresh').onclick=()=>{if(this.selected)openResearch(this.selected,{refresh:true,history:false,section:researchSection});else this.station(this.stationId||'sources',{history:false})};
    el('#atlasSave').onclick=()=>{if(this.selected){toggleFavorite(this.selected);this.stockTools()}};el('#atlasCompare').onclick=()=>{if(this.selected)addCompare(this.selected);this.station('compare')};el('#atlasNote').onclick=()=>{if(!this.selected)return;ROOT_VIEW('stock');this.openPane('Notes on '+this.selected);requestAnimationFrame(()=>{scrollResearchTo(el('#worldNotebook'));el('#worldNote')?.focus({preventScroll:true})})};
    this.canvas.addEventListener('pointerup',e=>{if(this.down?.moved>=7)return;const r=this.canvas.getBoundingClientRect();this.pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);this.raycaster.setFromCamera(this.pointer,this.camera);const hit=this.raycaster.intersectObjects(this.pickables).find(x=>x.object.userData.node?.kind==='station'||x.object.userData.node?.kind==='sector');if(hit){const n=hit.object.userData.node;n.kind==='sector'?this.district(n.id):this.station(n.id)}});
  }
  activate(){super.activate();document.body.classList.add('market-ready');el('#atlasLoading')?.remove();el('#explorer').classList.add('show');document.body.classList.add('research-open');document.body.style.overflow='hidden';el('.shell')?.setAttribute('inert','');el('.bottom-nav')?.setAttribute('inert','');}
  openPane(title){super.openPane(title);el('#universePaneKicker').textContent=(this.selected||'RECOVERY OS')+' / '+(this.selected?'COMPANY RESEARCH':'WORLD DESTINATION');}
  closePane(){document.body.classList.remove('atlas-reading');super.closePane();if(document.body.classList.contains('universe-mode'))el('.ex-main')?.setAttribute('inert','');}
  reading(value){if(value&&!document.body.classList.contains('universe-pane-open')){if(this.selected)selectResearchSection('brief',{scroll:false});else this.station('sectors')}document.body.classList.toggle('atlas-reading',value);el('#universeExpand').setAttribute('aria-label',value?'Return to the split research view':'Expand the research reader');this.resize()}
  location(title){el('#atlasLocation b').textContent=title;all('.universe-footer>div>button').forEach(b=>b.classList.toggle('selected',b.id===({home:'atlasHome',sectors:'atlasSectors',tracker:'universeTracker',news:'atlasNews',macro:'atlasMacro',workspace:'atlasWorkspace'}[this.stationId||this.locationKind])))}
  refreshData(){
    const rows=new Map(ATLAS_INDEX.map(r=>[r.ticker,r]));
    for(const record of this.registry){const next=rows.get(record.ticker);if(next)Object.assign(record,next)}
    this.records=OPEN_RESEARCH_INDEX;this.refreshTape();this.refreshPool(true);this.changed=true;
    if(this.stationId==='news')this.loadNews();
    if(this.stationId==='tracker')this.showStationPanel('Recovery Lab',this.trackerPanel());
    window.dispatchEvent(new CustomEvent('information-preferences'));
  }
  refreshTape(){const tickers=['SPY','QQQ','NVDA','AAPL','MSFT','DECK'];el('#atlasTape').innerHTML=tickers.map(t=>{const r=ATLAS_SYMBOLS.get(t);return r&&MODEL.finite(r.price)?`<button data-tape-symbol="${t}" title="${esc(r.quoteAsOf||'Observation date unavailable')}"><b>${t}</b><span>${fmtMoney(r.price)}</span><em class="${r.changePct>=0?'up':'down'}">${MODEL.finite(r.changePct)?fmtPct(r.changePct,2):'SOURCE'}</em></button>`:''}).join('')+`<small>DATED QUOTES · CHECK SYMBOL TIMESTAMPS</small>`;all('[data-tape-symbol]').forEach(b=>b.onclick=()=>openResearch(b.dataset.tapeSymbol))}
  home(history=true){
    researchRequest++;this.stopTour();this.selected=null;this.bundle=null;this.stationId=null;this.focusDistrict=null;this.locationKind='home';this.closePane();ROOT_VIEW('explore');this.portalGroup.visible=false;this.core.position.set(0,0,0);this.core.scale.setScalar(1.15);this.planet.visible=true;this.swapWordmark('RECOVERY');this.wordmark.position.y=190;this.wordmark.scale.set(132,23,1);el('#universeTitle').classList.remove('company-title');el('#universeTitle').innerHTML='The market.<br><em>In every direction.</em>';el('#universeSubtitle').textContent='An open universe of companies, ideas and evidence. Choose a destination. Follow your curiosity.';el('#universeStockMeta').innerHTML=`<span>${this.registry.length.toLocaleString()} searchable securities</span><span>${(ATLAS_META?.counts?.financials||0).toLocaleString()} with financial records</span>`;el('#universeGeneral').innerHTML='Explore the market <span>↗</span>';el('#universeGeneral').onclick=()=>this.station('sectors');el('#universeDestinations').innerHTML=STATIONS.map(([id,title],i)=>`<button data-atlas-station="${id}"><small>0${i+1}</small>${title}</button>`).join('');this.bindStations();this.stockTools();this.location('THE MARKET UNIVERSE');el('#universeTravelStatus').textContent='Drag to orbit · choose a floating destination · search any company';this.fly(new THREE.Vector3(0,58,0),mobile()?1060:790,.2,1.13);this.refreshPool(true);if(history)navRoute('#world');
  }
  overview(){this.home(false)}
  stock(b){
    this.locationKind='stock';this.stationId=null;const r=this.registryMap.get(b.profile.ticker);this.focusDistrict=r?.sector||null;if(r){const node=this.pool[0];node.id=r.ticker;node.base.copy(r.position);node.position.copy(r.position).setY(r.position.y+31)}this.planet.visible=false;this.core.scale.setScalar(1);super.stock(b);this.wordmark.position.y=70;this.stockTools();this.location(b.profile.ticker+' / RESEARCH WORLD');this.refreshPool(true);el('#universeStockMeta').insertAdjacentHTML('beforeend',b.profile.sector?`<button id="atlasStockSector">${esc(b.profile.sector)} district ↗</button>`:'');el('#atlasStockSector')?.addEventListener('click',()=>this.district(r?.sector||'Market frontier'));
  }
  stockTools(){el('#atlasStockTools').hidden=!this.selected;el('#atlasSave').textContent=this.selected&&user.favorites.includes(this.selected)?'★ Company saved':'☆ Save company'}
  district(id,options={}){
    const node=this.sectorNodes.find(n=>n.id===id);if(!node)return;researchRequest++;this.stopTour();this.locationKind='sector';this.stationId='sectors';this.focusDistrict=id;this.selected=null;this.bundle=null;this.portalGroup.visible=false;this.closePane();this.stockTools();this.location(node.title.toUpperCase()+' DISTRICT');el('#universeTitle').classList.remove('company-title');el('#universeTitle').textContent=node.title;el('#universeSubtitle').textContent='Explore the companies and the public evidence inside this sector.';const members=this.registry.filter(r=>r.sector===id);el('#universeStockMeta').innerHTML=`<span>${members.length.toLocaleString()} securities in this district</span>`;el('#universeGeneral').innerHTML='Browse this district <span>↗</span>';el('#universeGeneral').onclick=()=>this.sectorPanel(id);el('#universeDestinations').innerHTML=members.filter(x=>x.marketCap).sort((a,b)=>b.marketCap-a.marketCap).slice(0,10).map(x=>`<button data-tape-symbol="${x.ticker}">${x.ticker} ↗</button>`).join('');all('#universeDestinations [data-tape-symbol]').forEach(b=>b.onclick=()=>openResearch(b.dataset.tapeSymbol));this.fly(node.base.clone().setY(30),mobile()?900:650,.25,1.04);this.refreshPool(true);if(options.history!==false)navRoute('#atlas/sector/'+encodeURIComponent(id));
  }
  sectorPanel(id){const members=this.registry.filter(x=>x.sector===id);this.showStationPanel('Companies in '+id,`<div class="atlas-panel-head"><span class="research-kicker">SECTOR DISTRICT</span><h2>${esc(id)}</h2><p>${members.length.toLocaleString()} securities. Filter by name or ticker, then open a company world.</p></div><label class="sr-only" for="districtSearch">Search this district</label><input id="districtSearch" class="atlas-filter" type="search" placeholder="Filter this district…"><div id="districtCompanies"></div>`);const render=()=>{const q=el('#districtSearch').value.toLowerCase(),rows=members.filter(x=>(x.ticker+' '+x.name).toLowerCase().includes(q)).sort((a,b)=>(b.marketCap||0)-(a.marketCap||0));el('#districtCompanies').innerHTML=this.companyRows(rows.slice(0,80))+`<p class="source-note">Showing ${Math.min(rows.length,80)} of ${rows.length} matches. Narrow the filter to find any company.</p>`;this.bindCompanies()};el('#districtSearch').oninput=render;render();}
  bindStations(){all('[data-atlas-station]').forEach(b=>b.onclick=()=>this.station(b.dataset.atlasStation))}
  bindCompanies(){all('[data-atlas-company]').forEach(b=>b.onclick=()=>openResearch(b.dataset.atlasCompany));all('[data-atlas-thesis]').forEach(b=>b.onclick=()=>openResearch(b.dataset.atlasThesis,{section:'thesis'}))}
  companyRows(records){return `<div class="atlas-company-list">${records.map(x=>`<button data-atlas-company="${esc(x.ticker)}"><span><b>${esc(x.ticker)}</b><small>${esc(x.name||x.company||x.ticker)}</small></span><em>${MODEL.finite(x.price)?fmtMoney(x.price):'Open research ↗'}${MODEL.finite(x.changePct)?`<small class="${x.changePct>=0?'up':'down'}">${fmtPct(x.changePct,2)}</small>`:''}</em></button>`).join('')}</div>`}
  showStationPanel(title,html){all('.ex-view').forEach(v=>v.classList.toggle('active',v.id==='ex-atlas'));activeView='atlas';el('#ex-atlas').innerHTML=html;this.openPane(title);el('.ex-main').scrollTop=0;this.bindStations();this.bindCompanies();}
  station(id,options={}){
    researchRequest++;this.stopTour();this.stationId=id;this.locationKind='station';const node=this.stationNodes.find(n=>n.id===id||['compare','lists','screener'].includes(id)&&n.id==='workspace');this.focusDistrict=null;this.selected=null;this.bundle=null;this.portalGroup.visible=false;this.stockTools();this.location((node?.title||id).toUpperCase());
    const contents=id==='sectors'?this.sectorOverview():id==='tracker'?this.trackerPanel():id==='workspace'?this.workspacePanel():id==='sources'?this.sourcesPanel():id==='macro'?renderEvidenceMacro():id==='news'?this.newsPlaceholder():null;
    if(['compare','lists','screener'].includes(id)){ROOT_VIEW(id);this.openPane(({compare:'Compare companies',lists:'Saved lists & research',screener:'Stock screener'})[id])}else this.showStationPanel(node?.title||'Market research',contents||this.sourcesPanel());
    el('#universeTitle').classList.remove('company-title');el('#universeTitle').textContent=node?.title||'Compare';el('#universeSubtitle').textContent=node?.detail||'Inspect periods and values side by side.';el('#universeStockMeta').innerHTML='';el('#universeDestinations').innerHTML=STATIONS.map(([key,title])=>`<button class="${id===key?'selected':''}" data-atlas-station="${key}">${title}</button>`).join('');this.bindStations();
    all('[data-atlas-sector]').forEach(b=>b.onclick=()=>{this.district(b.dataset.atlasSector);this.sectorPanel(b.dataset.atlasSector)});el('#workspaceCompare')?.addEventListener('click',()=>this.station('compare'));el('#atlasTrackerRefresh')?.addEventListener('click',async()=>{await loadState(true);if(this.stationId==='tracker')this.station('tracker',{history:false})});el('#atlasTrackerExport')?.addEventListener('click',()=>el('#exportCommand').click());
    if(node)this.fly(node.base.clone().setY(28),mobile()?390:290,Math.atan2(node.base.x,node.base.z)+.23,1.16);if(id==='news')this.loadNews();if(options.history!==false)navRoute('#atlas/'+id);
  }
  sectorOverview(){return `<div class="atlas-panel-head"><span class="research-kicker">SECTOR ATLAS</span><h2>Choose a part of the market.</h2><p>Fly into a district, meet its companies, and follow their evidence.</p></div><div class="atlas-sector-grid">${this.sectors.map(s=>{const rows=this.registry.filter(r=>r.sector===s.id),quoted=rows.filter(r=>MODEL.finite(r.changePct)),up=quoted.filter(r=>r.changePct>0).length;return `<button data-atlas-sector="${esc(s.id)}" style="--sector-color:#${s.color.toString(16)}"><span class="atlas-sector-orbit">◎</span><b>${s.title} ↗</b><small>${rows.length.toLocaleString()} securities${quoted.length?' · '+up+' / '+quoted.length+' quoted higher':''}</small></button>`}).join('')}</div><p class="source-note">Districts use provider sector classifications. Quoted higher counts describe the stored screener sample; they are not a live breadth index.</p>`}
  trackerPanel(){const state=currentState();if(!state)return '<h2>Loading the recovery record…</h2>';return `<div class="atlas-panel-head"><span class="research-kicker">RECOVERY LAB / REV ${state.meta.revision}</span><h2>Follow the thesis.</h2><p>Watch the original crisis, catalyst and confirmation requirements develop together.</p></div><div class="research-metrics">${atlasStat('Qualified',String(state.scorecard.qualified),'Saved tracker')}${atlasStat('Provisional',String(state.scorecard.provisionalExceptionReview),'Exception review')}${atlasStat('Actionable',String(state.scorecard.actionable),'Saved entry checklist')}${atlasStat('Research queue',String(state.researchQueue?.length||0),'Ideas under investigation')}</div><p class="source-note">Market data: ${esc(state.meta.lastSuccessfulMarketRefresh||state.marketData?.asOf||'not refreshed')} · Full thesis scan: ${esc(state.meta.lastSuccessfulScan)}</p><div class="atlas-recovery-list">${state.stocks.map(x=>`<article><header><b>${esc(x.ticker)}</b><span>${esc(x.status)}</span></header><h4>${esc(x.company)}</h4><p><b>${fmtMoney(latestQuote(x).price)}</b> · ${esc(quoteLabel(x))} · ${fmtPct(latestSinceAdded(x),2)} from discovery</p><p>${esc(x.crisis.summary)}</p><div class="atlas-blocker"><span>NEXT CONFIRMATION</span>${esc(x.blocker)}</div><footer><button class="ex-btn" data-atlas-thesis="${esc(x.ticker)}">Open recovery thesis ↗</button><button class="ex-btn" data-atlas-company="${esc(x.ticker)}">General Research ↗</button></footer></article>`).join('')}</div><details class="atlas-detail"><summary>Changes & discovery history</summary>${[...(state.events||[])].reverse().map(x=>`<article class="atlas-history"><small>${esc(x.time)}</small><h4>${esc(x.ticker+' / '+x.title)}</h4><p>${esc(x.detail)}</p></article>`).join('')}</details><div class="public-source-links"><button class="ex-btn" id="atlasTrackerRefresh">Refresh saved tracker ↻</button><button class="ex-btn" id="atlasTrackerExport">Export tracker checkpoint ↓</button></div>`}
  workspacePanel(){const favorites=user.favorites.map(t=>ATLAS_SYMBOLS.get(t)||{ticker:t,name:t}),noted=Object.entries(user.notes||{}).filter(([,v])=>v?.trim());return `<div class="atlas-panel-head"><span class="research-kicker">YOUR WORKSPACE</span><h2>Keep the useful connections.</h2><p>Saved on this device. Open a company to continue your notes, bookmark sources or compare its evidence.</p></div><h3>Saved companies</h3>${favorites.length?this.companyRows(favorites):'<p class="atlas-prompt">Choose “Save company” inside any stock world to keep it here.</p>'}<h3>Your notes</h3>${noted.length?noted.map(([t,n])=>`<article class="atlas-note-preview"><button data-atlas-company="${esc(t)}">${esc(t)} ↗</button><p>${esc(n.slice(0,260))}${n.length>260?'…':''}</p></article>`).join(''):'<p class="atlas-prompt">Use Notes inside a company world to save the questions you want to revisit.</p>'}<div class="public-source-links"><button class="ex-btn" data-atlas-station="compare">Compare companies ↗</button><button class="ex-btn" data-atlas-station="lists">Saved lists & research ↗</button><button class="ex-btn" data-atlas-station="screener">Stock screener ↗</button></div><h3>Recently explored</h3>${this.companyRows((user.recent||[]).slice(0,10).map(x=>ATLAS_SYMBOLS.get(typeof x==='string'?x:x.ticker)||{ticker:typeof x==='string'?x:x.ticker}))}`}
  sourcesPanel(){const counts=ATLAS_META?.counts||{};return `<div class="atlas-panel-head"><span class="research-kicker">SOURCE ARCHIVE</span><h2>A way back to every fact.</h2><p>Evidence is collected from public sources and stays readable here when an upstream feed is unavailable.</p></div><div class="research-metrics">${atlasStat('Searchable securities',(counts.symbols||SYMBOLS.length).toLocaleString(),'Public company directory')}${atlasStat('Price snapshots',(counts.quotes||0).toLocaleString(),'Nasdaq source collection')}${atlasStat('Financial coverage',(counts.financials||0).toLocaleString(),'Securities with SEC records')}${atlasStat('Deeper histories',OPEN_RESEARCH_INDEX.length.toLocaleString(),'Prepared stock & ETF worlds')}</div><p class="source-note">Atlas collected ${esc(snapshotDate(ATLAS_META?.retrievedAt))}. Data is dated; exchange timestamps are shown only when provided. A snapshot is not a real-time feed.</p><div class="atlas-source-cards">${[['https://www.sec.gov/search-filings/edgar-application-programming-interfaces','SEC EDGAR','Financial statements, original filings and company identity'],['https://www.nasdaq.com/market-activity/stocks/screener','Nasdaq','Prices, market capitalization, sectors and industries'],['https://finance.yahoo.com/','Yahoo Finance','Daily price histories and news feeds'],['https://www.federalreserve.gov/feeds/feeds.htm','Federal Reserve','Monetary policy releases'],['https://www.bls.gov/feed/','Bureau of Labor Statistics','Inflation and employment releases'],['https://home.treasury.gov/treasury-daily-interest-rate-xml-feed','US Treasury','Treasury yield curve'],['https://fred.stlouisfed.org/','FRED','Federal economic time series']].map(([url,title,note])=>`<a href="${url}" target="_blank" rel="noopener noreferrer"><span>↗</span><strong>${title}</strong><p>${note}</p></a>`).join('')}</div><article class="research-prose"><h4>Read the evidence in context</h4><p>Company and calendar periods can differ. Ratios use compatible dates and units. Where no compatible figure is available, the original filing or source page is provided. Research scenarios describe questions to test; they do not create trades or qualify a recovery setup.</p></article>`}
  newsPlaceholder(){return `<div class="atlas-panel-head"><span class="research-kicker">NEWS OBSERVATORY</span><h2>Follow what changed.</h2><p>Company coverage and official releases, connected back to the research world.</p></div><div id="atlasNewsFeed" role="status"><p class="atlas-prompt">Opening the latest collected news records…</p></div>`}
  async loadNews(){const tickers=[...new Set([...user.favorites.slice(0,5),'AAPL','NVDA','MSFT','TSLA','PLTR','DECK','SPY','QQQ'])];const results=await Promise.allSettled(tickers.map(t=>researchBundle(t)));if(this.stationId!=='news')return;const published=await window.RecoveryRequests.json('data/news.json').catch(()=>({items:[]}));if(this.stationId!=='news')return;const items=[...(published.items||[]),...(OPEN_RESEARCH_MACRO?.releases||[]),...results.flatMap((r,i)=>r.status==='fulfilled'?(r.value.news||[]).map(n=>({...n,relatedTicker:tickers[i]})):[])].filter((x,i,a)=>MODEL.safeURL(x.url)&&a.findIndex(y=>y.url===x.url)===i).sort((a,b)=>String(b.published).localeCompare(String(a.published)));const feed=el('#atlasNewsFeed');if(!feed)return;feed.innerHTML=`<label class="sr-only" for="atlasNewsFilter">Filter news</label><input class="atlas-filter" id="atlasNewsFilter" type="search" placeholder="Filter companies, headlines or sources…"><div id="atlasNewsRows"></div><p class="source-note">Collected headlines are research leads. Publication time can differ from the event time; open the report to verify the claim.</p>`;const render=()=>{const q=el('#atlasNewsFilter').value.toLowerCase(),rows=items.filter(x=>(x.title+' '+x.publisher+' '+(x.relatedTicker||'')).toLowerCase().includes(q));el('#atlasNewsRows').innerHTML=rows.slice(0,45).map(x=>`<article class="atlas-news-item"><small>${esc(x.publisher)} · ${esc(snapshotDate(x.published))}</small><h4>${sourceLink(x.url,x.title)}</h4>${x.relatedTicker?`<button class="research-text-link" data-atlas-company="${x.relatedTicker}">Explore ${x.relatedTicker} ↗</button>`:'<span class="research-label">OFFICIAL MACRO RELEASE</span>'}</article>`).join('')||'<p class="atlas-prompt">No matching collected headlines. Change the filter or open a company’s public news sources.</p>';this.bindCompanies()};el('#atlasNewsFilter').oninput=render;render();}
  startTour(){if(this.tourTimer){this.stopTour();return}this.tourIndex=0;const stockTicker=this.selected;const route=stockTicker?['brief','price','financials','filings','catalysts','risks','macro','sources']:['sectors','tracker','news','macro','workspace','sources'];const next=()=>{const id=route[this.tourIndex%route.length];if(stockTicker&&currentBundle?.profile.ticker===stockTicker){ROOT_SELECT(id,{scroll:false});this.destination(id)}else this.station(id,{history:false});this.tourIndex++;this.tourTimer=setTimeout(next,11000);el('#universeTour').innerHTML='Pause flight <span>Ⅱ</span>'};next();}
  projectLabels(){
    this.refreshPool();const w=this.stage.clientWidth,h=this.stage.clientHeight,heading=el('.universe-heading').getBoundingClientRect(),panelOpen=document.body.classList.contains('universe-pane-open');const nodes=[...(this.selected?this.topicNodes:[]),...this.stationNodes,...this.sectorNodes,...this.pool.filter(n=>n.id&&n.id!==this.selected)];const priority=n=>n.kind==='topic'?0:n.kind==='station'&&this.locationKind==='home'?1:n.kind==='sector'&&this.locationKind==='home'?2:3;
    nodes.sort((a,b)=>priority(a)-priority(b)||a.position.distanceToSquared(this.camera.position)-b.position.distanceToSquared(this.camera.position));const placed=[];for(const node of this.labels)node.label.hidden=true;
    for(const n of nodes){if(n.kind==='topic')n.position.copy(n.local).add(this.portalGroup.position);if(n.kind==='company'&&this.focusDistrict&&this.registryMap.get(n.id)?.sector!==this.focusDistrict)continue;const v=n.position.clone().project(this.camera);if(v.z<0||v.z>1)continue;const x=(v.x+1)*w/2,y=(1-v.y)*h/2,bw=mobile()?148:n.kind==='company'?152:180,bh=72;if(x<bw/2+12||x>w-bw/2-12||y<(mobile()?163:127)||y>h-(panelOpen&&mobile()?20:150))continue;if(x-bw/2<heading.right+15&&y<heading.bottom+15)continue;if(placed.some(p=>Math.abs(p.x-x)<(p.w+bw)/2+9&&Math.abs(p.y-y)<bh+12))continue;if(placed.length>(mobile()?5:15))break;n.label.hidden=false;n.label.style.width=bw+'px';n.label.style.transform=`translate3d(${Math.round(x-bw/2)}px,${Math.round(y)}px,0)`;n.label.style.opacity='1';placed.push({x,y,w:bw});}
  }
  drawRadar(){if(!this.radar)return;const ctx=this.radar;ctx.clearRect(0,0,160,160);ctx.strokeStyle='#68b9ce44';for(const r of[25,50,72]){ctx.beginPath();ctx.arc(80,80,r,0,Math.PI*2);ctx.stroke()}for(const s of this.sectors){ctx.fillStyle='#91c6d3';ctx.fillRect(80+s.base.x*.055,80+s.base.z*.055,3,3)}const p=this.camera.position;ctx.fillStyle='#cff8ed';ctx.beginPath();ctx.arc(Math.max(5,Math.min(155,80+p.x*.055)),Math.max(5,Math.min(155,80+p.z*.055)),3,0,Math.PI*2);ctx.fill()}
  recoverRenderer(){const canvas=document.createElement('canvas');canvas.id='universeCanvas';canvas.tabIndex=0;canvas.setAttribute('aria-label','Interactive three-dimensional market universe');this.canvas.replaceWith(canvas);this.canvas=canvas;this.renderer=new HologramRenderer(canvas);this.canvas.dataset.renderer='perspective-canvas';this.bind();this.resize();this.active=true;}
}

function thesisReader(b){const x=tracked(b.profile.ticker);if(!x)return readerHeader('RECOVERY LAB','Build the research first.','This company does not have a saved recovery qualification.')+atlasSourceCards(b);return readerHeader('RECOVERY THESIS',x.ticker+' / '+x.status,'Saved crisis-to-recovery record. General research does not change the entry checklist.')+`<div class="research-metrics">${atlasStat('Latest',fmtMoney(x.latestPrice),x.quoteAsOf||'Tracker quote')}${atlasStat('Since discovery',fmtPct(x.sinceAddedPct,2),'Discovery '+fmtMoney(x.discoveryPrice))}${atlasStat('Entry eligible',x.entryEligible,'Saved tracker')}${atlasStat('Setup progress',x.progress+'%','Saved tracker')}${atlasStat('Tier',x.tier,'Recovery classification')}</div>`+[['Original crisis',x.crisis?.summary],['Recovery catalyst',x.catalyst?.summary],['What remains unresolved',x.blocker],['Fundamental invalidation',x.setup?.fundamentalInvalidation],['Event restriction',x.setup?.eventRestriction]].filter(([,v])=>v).map(([title,v],i)=>evidenceCard(i+1,title,[v])).join('')+`<h4>Confirmation checklist</h4><div class="atlas-checklist">${(x.checklist||[]).map(c=>`<div><span>${esc(c.name)}</span><b>${esc(c.state)}</b></div>`).join('')}</div><h4>Original evidence</h4>${(x.evidence||[]).map(e=>`<article class="atlas-news-item"><small>${esc(e.sourceType)}</small><h4>${sourceLink(e.url,e.title)}</h4><p>${esc(e.claim||'')}</p></article>`).join('')}<button class="ex-btn" data-research-section="brief">Continue General Research ↗</button>`}
RESEARCH_TOPICS.push(['thesis','09','Recovery thesis','Original recovery conditions']);
renderResearchReader=function renderWorldReader(section,b,a,tr){if(section==='thesis'){cleanupResearch();el('#researchReader').innerHTML=thesisReader(b);bindResearchNavigation()}else ROOT_READER(section,b,a,tr)};
openExplorer=function openWorld(view='explore'){ROOT_OPEN(view);if(!market)return;market.activate();if(view==='explore')market.home(false);else if(view!=='stock')market.station(view)};
closeExplorer=function returnToUniverse(){if(market)market.home();};
showView=function showWorldView(id){if(!market)return ROOT_VIEW(id);if(id==='explore')market.home();else if(id==='stock'){ROOT_VIEW(id);if(currentBundle)market.stock(currentBundle)}else market.station(id)};
openResearch=async function openCompanyWorld(raw,options={}){if(window.RecoveryFabric?.replayState)window.RecoveryFabric.exitReplay();document.body.classList.remove('information-open');const parts=String(raw||'').split('/'),prefix=parts[0].split(':');prefix[prefix.length-1]=symbolKey(prefix.at(-1));parts[0]=prefix.join(':');if(market){market.activate();market.stopTour();market.closePane();el('#universeTravelStatus').textContent='Opening '+prefix.at(-1)+' · collecting the available evidence';el('#universeGeneral').onclick=()=>selectResearchSection('brief',{scroll:false})}return ROOT_RESEARCH(parts.join('/'),options)};
renderResearchWorld=function renderCompanyWorld(b,section='brief'){ROOT_RENDER(b,section);if(market){market.stock(b);if(section!=='brief'){ROOT_SELECT(section,{scroll:false});market.destination(section)}}};
selectResearchSection=function visitResearchDestination(section,options={}){if(window.RecoveryFabric?.replayState)window.RecoveryFabric.exitReplay();document.body.classList.remove('information-open');if(!currentBundle||!RESEARCH_TOPICS.some(x=>x[0]===section))return;ROOT_SELECT(section,{...options,scroll:false});if(market){market.stopTour();ROOT_VIEW('stock');if(market.bundle!==currentBundle)market.stock(currentBundle);market.destination(section);window.RecoveryFabric?.onStock(currentBundle);if(section==='thesis')el('#universePaneTitle').textContent='Recovery thesis'}};
openRoom=function openRecoveryWorld(t){return openResearch(t,{section:'thesis'})};

async function routeWorld(){if(routeBusy||!market)return;routeBusy=true;try{const hash=location.hash;if(hash.startsWith('#research/')){let path;try{path=decodeURIComponent(hash.slice(10))}catch{market.home(false);return}const [raw,section='brief']=path.split('/'),t=symbolKey(raw.split(':').at(-1));if(t===currentTicker&&currentBundle){ROOT_VIEW('stock');market.stock(currentBundle);if(section!=='brief')selectResearchSection(section,{history:false})}else await openResearch(path,{history:false})}else if(hash.startsWith('#atlas/sector/'))market.district(decodeURIComponent(hash.slice(14)),{history:false});else if(hash.startsWith('#atlas/'))market.station(hash.slice(7),{history:false});else market.home(false)}finally{routeBusy=false}}
function bootMarket(){if(market)return;market=new MarketWorld();if(market.failed){market=null;el('#atlasLoading')?.remove();document.body.classList.remove('market-world-app','universe-mode');ROOT_OPEN('explore');return}market.activate();installInformationWorld(market);window.RecoveryUniverse={open:()=>market.home(),route:routeWorld,read:()=>market.reading(true)};window.RecoveryExplorer={open:openExplorer,openResearch,showView};go=id=>market.station(({tracker:'tracker',history:'tracker',command:'tracker',alerts:'news',world:'sectors'})[id]||'sectors');routeWorld();}
window.addEventListener('market-atlas-ready',()=>requestAnimationFrame(bootMarket));if(window.marketAtlasReady)requestAnimationFrame(bootMarket);
