/* Movement reader: published evidence, shared snapshots and historical cutoffs. */
(()=>{'use strict';
const M=window.RecoveryMovement,F=window.RecoveryInformation,U=window.RecoveryFabric,H=window.RecoveryHistory;
const esc=U.escape,$=s=>document.querySelector(s),cache=new Map(),pending=new Map(),checked=new Map(),states=new WeakMap();
let dialogState=null;
const fmt=v=>F.finite(v)?`${v>0?'+':''}${v.toFixed(2)}%`:'Unavailable';
const money=(v,c)=>F.finite(v)?new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(v)+(c?' '+c:''):'Unavailable';
const when=t=>t?F.display(t):'Not supplied';
const published=e=>e.evidence[0].timestampPrecision==='DAY'?M.etDay(Date.parse(e.evidence[0].publishedAt||e.publishedAt)-1)+' · exact time not supplied':when(e.evidence[0].publishedAt||e.publishedAt);
const link=(url,label)=>F.safeURL(url)?`<a href="${esc(F.safeURL(url))}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`:'<span>Source link unavailable</span>';
function macroEvents(data){return (data?.releases||[]).filter(n=>/interest rate|monetary|fomc|inflation|consumer price|producer price|employment|payroll|gross domestic|\bgdp\b|unemployment|retail sales/i.test(n.title||'')).map(n=>F.event('macro',n.title,{publishedAt:n.published,effectiveAt:n.eventDate,detectedAt:n.retrievedAt||data.retrievedAt,evidence:[F.source({provider:n.publisher,url:n.url,sourceType:'GOVERNMENT',publishedAt:n.published,effectiveAt:n.eventDate,retrievedAt:n.retrievedAt||data.retrievedAt})],sourceType:'GOVERNMENT',url:n.url},{eventTimeKnown:!!n.eventDate}));}
async function load(ticker,{refresh=false}={}){
 if(pending.has(ticker))return pending.get(ticker);
 const previous=cache.get(ticker);if(previous&&!refresh&&Date.now()-previous.at<300000)return previous;
 const old=H.current.get(ticker),stale=!old?.sourceRetrievedAt||Date.now()-Date.parse(old.sourceRetrievedAt)>86400000;
 const force=refresh||(stale&&Date.now()-(checked.get(ticker)||0)>300000);checked.set(ticker,Date.now());
 const task=(async()=>{
  const d=await U.load(ticker,{refresh:force});
  const sector=M.SECTORS[d.metrics.sector?.value]||null;
  const symbols=[...new Set([sector,'SPY','QQQ','IWM'].filter(t=>t&&t!==ticker))];
  const results=await Promise.allSettled(symbols.map(t=>U.load(t,{refresh:force})));
  const peers=new Map(results.flatMap((r,i)=>r.status==='fulfilled'?[[symbols[i],r.value]]:[]));peers.set(ticker,d);
  const macro=await window.RecoveryRequests.json('data/open-research/macro.json',{refresh:force}).catch(()=>null);
  const entry={d,sector,peers,macro:macroEvents(macro),at:Date.now(),checkedAt:new Date().toISOString(),error:null};
  cache.set(ticker,entry);while(cache.size>30)cache.delete(cache.keys().next().value);return entry;
 })();pending.set(ticker,task);try{return await task}catch(e){if(previous)return {...previous,error:'The refresh failed. Retained evidence keeps its original dates.'};throw e}finally{pending.delete(ticker)}
}
function explain(entry,state){const bs=[{ticker:state.benchmark,role:'Market benchmark',dossier:entry.peers.get(state.benchmark)}];if(entry.sector)bs.unshift({ticker:entry.sector,role:'Sector proxy',dossier:entry.peers.get(entry.sector)});return M.analyze(entry.d,{period:state.period,cutoff:state.cutoff,mode:state.mode,benchmarks:bs,macro:entry.macro})}
function sourceBlock(s){return `<details class="movement-source"><summary>Source & calculation metadata</summary>${U.sourceHTML(F.source(s||{}))}</details>`}
function renderResult(r,entry){
 const p=r.move,has=F.finite(p.pct),polarity=r.evidence.filter(e=>/Bullish|Bearish|Mixed/.test(e.direction));
 const lastHeadline=r.evidence.map(e=>e.publishedAt).sort().at(-1);
 const coverage=F.coverage(entry.d,Date.parse(r.window.end)).filter(c=>['prices','news','announcements','filings'].includes(c.id));
 const timeline=r.timeline.slice(-100);
 return `<div class="movement-period"><span>${r.historical?'HISTORICAL · '+esc(r.mode)+' knowledge':'DATED EVIDENCE'}</span><p>${esc(when(r.window.start))} → ${esc(when(r.window.end))}</p><strong class="movement-return">${has?fmt(p.pct):p.price!=null?money(p.price,p.source.currency):'Explore source records'}</strong><p>${has?esc(p.method):p.price!=null?'Latest dated price · selected-period return still needs matching history':'No verified price observation in this dataset'}</p>${p.from?`<p>Measured closes: ${esc(when(p.from))} → ${esc(when(p.to))}<br>${money(p.baselinePrice,p.source.currency)} → ${money(p.price,p.source.currency)}</p>`:p.quoteAt?`<p>Latest dated price: ${money(p.price,p.source.currency)} · ${esc(when(p.quoteAt))}</p>`:''}<p class="movement-note">${esc(p.reason)}</p>${sourceBlock({...p.source,method:p.method,reportingPeriod:{start:p.from,end:p.to,scope:p.basis||'unavailable'},inputs:p.baselinePrice?[{value:p.baselinePrice,date:p.from,source:p.source.url},{value:p.price,date:p.to,source:p.source.url}]:[]})}</div>
 ${window.RecoveryPublicSources?.html(entry.d,{start:r.window.start,end:r.window.end})||''}
 <div class="movement-summary"><h3>${esc(r.verdict)}</h3><p>${esc(r.summary)}</p>${has?`<p>${esc(r.ticker)} ${p.pct>0?'rose':p.pct<0?'fell':'was unchanged'} ${fmt(p.pct)} on the stated price basis. This does not establish why.</p>`:'<p>The available prices cannot verify a rise or fall over the selected period.</p>'}${polarity.some(e=>e.direction==='Bullish factor')&&polarity.some(e=>e.direction==='Bearish factor')?'<p>Evidence is mixed: both bullish and bearish factors appear below.</p>':''}</div>
 <details open><summary>Company versus market</summary><p>${esc(r.context)}</p><div class="movement-context">${r.comparisons.map(c=>`<article><h4>${esc(c.role)} · ${esc(c.ticker)}</h4><strong>${fmt(c.move?.pct)}</strong><p>${c.move?.to?'As of '+esc(when(c.move.to)):'Matching-period prices unavailable'}</p>${c.comparable?`<p>Stock minus proxy: ${c.excess>0?'+':''}${c.excess.toFixed(2)} percentage points</p>`:''}<p>${esc(c.note)}</p>${c.move?sourceBlock(c.move.source):''}</article>`).join('')}</div><p class="movement-note">${entry.sector?'Sector proxy selected from the current directory classification ('+esc(entry.d.metrics.sector.value)+').':'No verified sector ETF mapping for this security.'} SPY represents broad U.S. equities; QQQ and IWM are alternative style proxies. ETF returns are not the company’s peer group and may not fit foreign listings or funds.${r.historical?' Historical sector membership is unverified; sector comparisons are contextual only.':''}</p></details>
 <details open><summary>Specific evidence · ${r.evidence.length}</summary><p class="movement-note">Ranked by original-source authority, company relevance and timing—not the likelihood of causation. Headline-based interpretation; open the source for the full report.</p>${r.evidence.length?r.evidence.map(e=>`<article class="movement-evidence"><div class="movement-labels"><span>${esc(e.factLabel)}</span><span>${esc(e.label)}</span><span>${esc(e.direction)}</span></div><h4>${link(e.evidence[0].url,e.title)}</h4><p>${esc(e.evidence[0].provider)} · Published ${esc(published(e))}${e.payload?.updatedAt?' · Updated version available '+esc(when(e.payload.updatedAt)):''}</p><p>Event time: ${esc(when(e.eventAt))}${!e.eventAt?' · Publication time is not being substituted for event time.':''}</p><p><b>Possible mechanism:</b> ${esc(e.mechanism)}</p><p><b>Price sequence:</b> ${esc(e.timing)}</p><p class="movement-note">${esc(e.strength)} · ${esc(e.rankingReason)}</p><button type="button" data-evidence-save="${esc(e.id)}">Bookmark evidence</button>${sourceBlock(e.evidence[0])}</article>`).join(''):'<p>No eligible company headline, filing or relevant official economic release was found in this period. A lack of coverage is not proof that nothing happened.</p>'}</details>
 <details><summary>News-and-price timeline · ${timeline.length} observations</summary><p>Publication markers and dated prices share one sequence. Daily observations do not show an intraday reaction. Event occurrence times, if supplied, are listed on each evidence card.</p><ol class="movement-timeline">${timeline.map(x=>`<li><time>${esc(x.type==='event'?(x.event.payload?.updatedAt?'Updated '+when(x.at):published(x.event)):x.type==='price'?M.etDay(Date.parse(x.at)-1)+' · close time not supplied':when(x.at))}</time><b>${esc(x.type==='event'?x.event.category:x.type)}</b><p>${x.type==='event'?link(x.event.evidence[0].url,x.title):esc(x.title)+' · '+money(x.price,x.source?.currency)}</p>${x.type==='event'?`<small>${esc(x.event.timing)}</small>`:link(x.source?.url,'Price source')}</li>`).join('')||'<li>No dated observations are available in this period.</li>'}</ol>${r.timeline.length>100?'<p>Showing the latest 100 observations. Narrow the period to inspect earlier entries.</p>':''}</details>
 <details><summary>Coverage, freshness & limitations</summary><p>Source last checked: ${esc(when(r.lastSourceCheck))}<br>Latest eligible publication: ${esc(when(lastHeadline))}<br>Published data checked by this view: ${esc(when(entry.checkedAt))}</p><p>Daily source collection and quote updates feed this view. Refresh checks the latest published evidence and any configured research API; it cannot make an unavailable upstream source current.</p>${entry.error?`<p role="alert">${esc(entry.error)}</p>`:''}<ul>${coverage.map(c=>`<li>${esc(c.label)}: ${esc(c.status)} · ${esc(c.reason||c.coverage)}</li>`).join('')}${r.limitations.map(t=>`<li>${esc(t)}</li>`).join('')}</ul><p>${r.historical?'Coverage above describes the retained source dossier, not a historical coverage claim. Historical explanation inputs remain cutoff-filtered.':''}</p></details>`;
}
function shell(state){return `<section class="movement-content" aria-label="Why Is This Stock Moving?"><p class="movement-intro">${esc(state.ticker)} · Evidence first. Explanations are conditional until price timing and reporting support them.</p><div class="movement-controls"><label>Explain<select data-movement-period>${Object.entries(M.PERIODS).map(([v,t])=>`<option value="${v}" ${state.period===v?'selected':''}>${t}${state.cutoff?' at cutoff':''}</option>`).join('')}</select></label><label>Benchmark<select data-movement-benchmark>${['SPY','QQQ','IWM'].map(t=>`<option ${state.benchmark===t?'selected':''}>${t}</option>`).join('')}</select></label><button type="button" data-movement-refresh>Refresh evidence ↻</button></div><div class="movement-status" role="status" aria-live="polite">Loading dated evidence…</div><div class="movement-result"></div><div class="movement-links"><button type="button" data-stock-coverage="${esc(state.ticker)}">Data Coverage Center</button><button type="button" data-stock-changes="${esc(state.ticker)}">What Changed?</button><button type="button" data-stock-replay="${esc(state.ticker)}" ${state.cutoff?`data-replay-date="${esc(state.cutoff)}"`:''}>Recovery Time Machine</button></div></section>`}
async function draw(host,state,refresh=false){
 const token=(state.token||0)+1;state.token=token;
 const button=host.querySelector('[data-movement-refresh]'),status=host.querySelector('.movement-status');if(!status)return;button.disabled=true;status.textContent=refresh?'Checking the latest published evidence…':'Loading dated evidence…';
 try{const entry=await load(state.ticker,{refresh});if(state.token!==token||!host.isConnected)return;const r=explain(entry,state);host.querySelector('.movement-result').innerHTML=renderResult(r,entry);status.textContent='Checked '+when(entry.checkedAt)+(entry.error?' · Retained evidence':' · '+(r.move.pct==null?'Price coverage incomplete':'Dated evidence'));U.bind(host);}
 catch{if(state.token===token&&host.isConnected){status.textContent='Evidence could not be loaded. Try refresh when connected.';host.querySelector('.movement-result').innerHTML='<p>No confirmed catalyst found. Price, news and benchmark data are unavailable; no explanation has been invented.</p>';}}
 finally{if(state.token===token&&host.isConnected)button.disabled=false;}
}
function wire(host,state){states.set(host,state);host.innerHTML=shell(state);host.querySelector('[data-movement-period]').onchange=e=>{state.period=e.target.value;draw(host,state)};host.querySelector('[data-movement-benchmark]').onchange=e=>{state.benchmark=e.target.value;draw(host,state)};host.querySelector('[data-movement-refresh]').onclick=()=>draw(host,state,true);U.bind(host);draw(host,state);}
function mount(ticker){const reader=$('#researchReader');if(!reader||reader.querySelector('.movement-section'))return;const section=document.createElement('details');section.className='movement-section';section.innerHTML='<summary><span>Why Is This Stock Moving?</span><small>Price, news & market evidence</small></summary><div class="movement-host"></div>';reader.prepend(section);load(ticker).catch(()=>{});const state={ticker,period:'today',benchmark:'SPY',cutoff:null,mode:'public'};section.addEventListener('toggle',()=>{if(section.open&&!states.has(section.querySelector('.movement-host')))wire(section.querySelector('.movement-host'),state)});}
function open(ticker,{cutoff=null,mode='public'}={}){const replay=U.replayState;if(replay?.ticker===ticker&&!cutoff){cutoff=replay.view.cutoff;mode=replay.view.mode}const state={ticker,period:'today',benchmark:'SPY',cutoff,mode};U.modal('Why Is This Stock Moving?',`<div id="movementDialogHost"></div>`);dialogState=state;wire($('#movementDialogHost'),state);}
// The shared modal preserves the replay cutoff and world camera.
document.addEventListener('click',e=>{if(e.target.closest('.movement-links'))$('#informationDialog')?.close();},true);
document.addEventListener('click',e=>{const b=e.target.closest('[data-stock-movement]');if(b){e.preventDefault();open(b.dataset.stockMovement,{cutoff:b.dataset.movementCutoff||null,mode:b.dataset.movementMode||'public'})}});
const originalReader=renderResearchReader;renderResearchReader=function(section,b,...rest){originalReader(section,b,...rest);mount(b.profile.ticker)};
window.addEventListener('information-dossier',e=>{if(U.world?.selected===e.detail.identity.ticker)mount(e.detail.identity.ticker)});
window.addEventListener('recovery-data-updated',()=>{cache.clear();for(const host of document.querySelectorAll('.movement-host,#movementDialogHost')){const state=states.get(host);if(state&&!state.cutoff)draw(host,state,true)}});
window.addEventListener('information-replay',e=>{const host=$('#movementDialogHost');if(!host||!$('#informationDialog')?.open||!dialogState)return;if(e.detail?.ticker===dialogState.ticker){dialogState.cutoff=e.detail.view.cutoff;dialogState.mode=e.detail.view.mode;wire(host,dialogState)}else if(!e.detail&&dialogState.cutoff){dialogState.cutoff=null;wire(host,dialogState)}});
window.RecoveryMovementUI={open,mount,load,macroEvents,renderResult,invalidate:()=>cache.clear()};
})();
