/* Open research paths supplement saved evidence; search results are not verified facts. */
(()=>{'use strict';
 const F=window.RecoveryInformation,U=window.RecoveryFabric,esc=U.escape;
 const official={AMZN:['Amazon News','https://www.aboutamazon.com/news'],AMD:['AMD Newsroom','https://newsroom.amd.com/'],AAPL:['Apple Newsroom','https://www.apple.com/newsroom/'],NVDA:['NVIDIA Newsroom','https://nvidianews.nvidia.com/'],META:['Meta Newsroom','https://about.fb.com/news/'],GOOGL:['Google The Keyword','https://blog.google/'],GOOG:['Google The Keyword','https://blog.google/'],MSFT:['Microsoft News','https://news.microsoft.com/'],ENPH:['Enphase investor relations','https://investor.enphase.com/'],ON:['onsemi investor relations','https://investor.onsemi.com/']};
 function links(d,{start=null,end=null}={}){const t=d.identity.ticker,name=d.identity.name||t,q=encodeURIComponent(name+' '+t),range=start&&end?' after:'+start.slice(0,10)+' before:'+new Date(Date.parse(end)+86400000).toISOString().slice(0,10):'';
  const rows=[['Search public news','https://news.google.com/search?q='+encodeURIComponent(name+' '+t+range)+'&hl=en-US&gl=US&ceid=US:en','DISCOVERY','Search beyond the collected feeds. Results need source and date verification; publishers may restrict full articles.'],['Official SEC records',d.identity.cik?'https://www.sec.gov/edgar/browse/?CIK='+encodeURIComponent(d.identity.cik)+'&owner=exclude':'https://www.sec.gov/edgar/search/#/q='+q,'OFFICIAL','Original filings, annual reports and company disclosures.'],['Find investor relations','https://www.google.com/search?q='+q+'+investor+relations','DISCOVERY','Find the issuer’s official earnings, presentations and announcements.'],['Explore price history','https://finance.yahoo.com/quote/'+encodeURIComponent(t)+'/history/','EXTERNAL PRICE VIEW','Open the provider’s dated table. An external link is not an imported or verified price series.'],['Search company reporting','https://www.google.com/search?q='+q+'+stock+news'+encodeURIComponent(range),'DISCOVERY','Compare independent reporting and original announcements.']];
  if(official[t])rows.unshift([...official[t],'OFFICIAL','Issuer-published news and announcements.']);
  return rows.map(([label,url,type,note])=>({label,url:F.safeURL(url),type,note})).filter(x=>x.url);
 }
 function html(d,options={}){return `<section class="public-research-paths"><h3>Keep exploring ${esc(d.identity.ticker)}</h3><p>Follow public sources beyond the saved dataset. Search links are research paths, not confirmed evidence or an assertion that nothing else happened.</p><div class="public-research-grid">${links(d,options).map(x=>`<a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer"><small>${esc(x.type)}</small><strong>${esc(x.label)} ↗</strong><span>${esc(x.note)}</span></a>`).join('')}</div>${options.end?'<p>Search is date-filtered where supported. Always verify publication and revision dates before using a result in historical research.</p>':''}</section>`}
 async function open(ticker){U.modal('Explore public sources',`<div id="publicSourcesContent">Opening source paths for ${esc(ticker)}…</div>`);const d=await U.load(ticker);const host=document.querySelector('#publicSourcesContent');if(host)host.innerHTML=html(d);}
 const reader=renderResearchReader;renderResearchReader=function(section,b,...args){reader(section,b,...args);const host=document.querySelector('#researchReader');if(host&&!host.querySelector('.public-source-launch'))host.insertAdjacentHTML('afterbegin',`<button class="public-source-launch ex-btn" data-public-sources="${esc(b.profile.ticker)}">Explore public sources ↗</button>`)};
 document.addEventListener('click',e=>{const b=e.target.closest('[data-public-sources]');if(b){e.preventDefault();open(b.dataset.publicSources)}});
 window.RecoveryPublicSources={links,html,open};
})();
