(()=>{
'use strict';
const avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:null;
function sma(vals,n){return vals.map((_,i)=>i+1<n?null:avg(vals.slice(i-n+1,i+1)))}
function ema(vals,n){const k=2/(n+1);let e=null;return vals.map((v,i)=>{if(v==null)return null;if(e==null){if(i<n-1)return null;e=avg(vals.slice(0,n));return e}e=v*k+e*(1-k);return e})}
function rsi(vals,n=14){let out=Array(vals.length).fill(null),g=0,l=0;if(vals.length<=n)return out;for(let i=1;i<=n;i++){const d=vals[i]-vals[i-1];g+=Math.max(d,0);l+=Math.max(-d,0)}g/=n;l/=n;out[n]=l===0?(g===0?50:100):100-100/(1+g/l);for(let i=n+1;i<vals.length;i++){const d=vals[i]-vals[i-1];g=(g*(n-1)+Math.max(d,0))/n;l=(l*(n-1)+Math.max(-d,0))/n;out[i]=l===0?(g===0?50:100):100-100/(1+g/l)}return out}
function atr(bars,n=14){const tr=bars.map((b,i)=>i===0?b.high-b.low:Math.max(b.high-b.low,Math.abs(b.high-bars[i-1].close),Math.abs(b.low-bars[i-1].close)));let out=Array(tr.length).fill(null);if(tr.length<n)return out;let value=avg(tr.slice(0,n));out[n-1]=value;for(let i=n;i<tr.length;i++){value=(value*(n-1)+tr[i])/n;out[i]=value}return out}
function macd(vals){const e12=ema(vals,12),e26=ema(vals,26),line=vals.map((_,i)=>e12[i]!=null&&e26[i]!=null?e12[i]-e26[i]:null),valid=line.filter(v=>v!=null),signalValues=ema(valid,9),offset=line.length-valid.length,signal=line.map((v,i)=>i<offset?null:signalValues[i-offset]),hist=line.map((v,i)=>v==null||signal[i]==null?null:v-signal[i]);return{line,signal,hist}}
function fmt(v,d=2){return v==null?'—':Number(v).toFixed(d)}
class RecoveryResearchChart{
 constructor(canvas,legend){this.c=canvas;this.ctx=canvas.getContext('2d');this.legend=legend;this.bars=[];this.comparison=null;this.opts={sma20:true,sma50:false,rsi:false,macd:false,atr:false,vwap:true};this.hover=null;this.handlers={move:e=>this.pointer(e),leave:()=>{this.hover=null;this.draw()}};this.ro=new ResizeObserver(()=>this.draw());this.ro.observe(canvas);canvas.addEventListener('pointermove',this.handlers.move);canvas.addEventListener('pointerdown',this.handlers.move);canvas.addEventListener('pointerleave',this.handlers.leave)}
 destroy(){this.ro.disconnect();this.c.removeEventListener('pointermove',this.handlers.move);this.c.removeEventListener('pointerdown',this.handlers.move);this.c.removeEventListener('pointerleave',this.handlers.leave)}
 setData(bars){this.bars=(bars||[]).map(b=>({...b}));this.hover=null;this.draw()}
 setComparison(label,bars){this.comparison=bars&&bars.length?{label,bars}:null;this.draw()}
 setOptions(o){Object.assign(this.opts,o);this.draw()}
 pointer(e){if(!this.bars.length)return;const r=this.c.getBoundingClientRect(),x=e.clientX-r.left,pad=48,w=r.width-pad-10;this.hover=Math.max(0,Math.min(this.bars.length-1,Math.round((x-pad)/Math.max(1,w/(this.bars.length-1)))));this.draw()}
 setup(){const r=this.c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2),w=Math.max(260,r.width),h=Math.max(220,r.height);if(this.c.width!==Math.round(w*d)||this.c.height!==Math.round(h*d)){this.c.width=Math.round(w*d);this.c.height=Math.round(h*d)}this.ctx.setTransform(d,0,0,d,0,0);return{w,h}}
 draw(){const {w,h}=this.setup(),g=this.ctx,b=this.bars;g.clearRect(0,0,w,h);g.fillStyle='#03090e';g.fillRect(0,0,w,h);if(!b.length){g.fillStyle='#668696';g.font='11px system-ui';g.fillText('NO VERIFIED PRICE BARS',18,30);return}
  const lower=this.opts.rsi||this.opts.macd?96:0,volH=52,padL=48,padR=10,padT=14,padB=20,mainH=h-padT-padB-volH-lower,plotW=w-padL-padR;
  const highs=b.map(x=>x.high),lows=b.map(x=>x.low),max=Math.max(...highs),min=Math.min(...lows),range=max-min||1,xStep=plotW/Math.max(1,b.length-1),x=i=>padL+i*xStep,y=v=>padT+(max-v)/range*mainH;
  g.strokeStyle='rgba(124,234,255,.07)';g.lineWidth=1;for(let i=0;i<=4;i++){const yy=padT+i*mainH/4;g.beginPath();g.moveTo(padL,yy);g.lineTo(w-padR,yy);g.stroke();const val=max-range*i/4;g.fillStyle='#577786';g.font='10px ui-monospace';g.textAlign='right';g.fillText('$'+fmt(val),padL-5,yy+3)}
  const closes=b.map(z=>z.close),s20=sma(closes,20),s50=sma(closes,50),mxv=Math.max(1,...b.map(z=>z.volume||0));
  b.forEach((z,i)=>{const xx=x(i),up=z.close>=z.open,col=up?'rgba(99,242,178,.78)':'rgba(255,114,140,.78)',bw=Math.max(2,Math.min(9,xStep*.62));g.strokeStyle=col;g.beginPath();g.moveTo(xx,y(z.high));g.lineTo(xx,y(z.low));g.stroke();g.fillStyle=col;const yo=y(Math.max(z.open,z.close)),yc=y(Math.min(z.open,z.close));g.fillRect(xx-bw/2,yo,bw,Math.max(1,yc-yo));const vh=(z.volume||0)/mxv*(volH-12);g.fillStyle=up?'rgba(99,242,178,.25)':'rgba(255,114,140,.25)';g.fillRect(xx-bw/2,padT+mainH+volH-vh,bw,vh)});
  const line=(arr,color)=>{g.strokeStyle=color;g.lineWidth=1.3;g.beginPath();let started=false;arr.forEach((v,i)=>{if(v==null)return;const xx=x(i),yy=y(v);started?g.lineTo(xx,yy):g.moveTo(xx,yy);started=true});g.stroke()};
  if(this.opts.sma20)line(s20,'rgba(124,234,255,.9)');if(this.opts.sma50)line(s50,'rgba(167,139,250,.9)');if(this.opts.vwap)line(b.map(z=>z.vwap),'rgba(245,198,110,.70)');
  let compLegend=null;if(this.comparison?.bars?.length){const byDate=new Map(this.comparison.bars.map(z=>[z.date,z.close])),baseStock=b.find(z=>byDate.has(z.date))?.close,baseComp=this.comparison.bars.find(z=>b.some(q=>q.date===z.date))?.close;if(baseStock&&baseComp){const arr=b.map(z=>byDate.has(z.date)?baseStock*(byDate.get(z.date)/baseComp):null);line(arr,'rgba(255,167,95,.82)');const first=arr.find(v=>v!=null),last=[...arr].reverse().find(v=>v!=null);compLegend=first&&last?`${this.comparison.label} REL ${((last/first-1)*100).toFixed(1)}%`:this.comparison.label}}
  let lowerTop=padT+mainH+volH+6,latestExtra=[];
  if(this.opts.rsi){const rr=rsi(closes),ph=lower-12;g.strokeStyle='rgba(124,234,255,.08)';[30,50,70].forEach(v=>{const yy=lowerTop+(100-v)/100*ph;g.beginPath();g.moveTo(padL,yy);g.lineTo(w-padR,yy);g.stroke();g.fillStyle='#4e6f7e';g.font='7px ui-monospace';g.textAlign='right';g.fillText(v,padL-5,yy+2)});g.strokeStyle='rgba(99,242,178,.8)';g.beginPath();let st=false;rr.forEach((v,i)=>{if(v==null)return;const xx=x(i),yy=lowerTop+(100-v)/100*ph;st?g.lineTo(xx,yy):g.moveTo(xx,yy);st=true});g.stroke();latestExtra.push(`RSI14 ${fmt(rr.at(-1),1)}`)}
  if(this.opts.macd){const mm=macd(closes),ph=lower-12,vals=[...mm.line,...mm.signal].filter(v=>v!=null),lo=Math.min(...vals,0),hi=Math.max(...vals,0),rg=hi-lo||1,yy=v=>lowerTop+(hi-v)/rg*ph;g.strokeStyle='rgba(124,234,255,.75)';g.beginPath();let st=false;mm.line.forEach((v,i)=>{if(v==null)return;st?g.lineTo(x(i),yy(v)):g.moveTo(x(i),yy(v));st=true});g.stroke();g.strokeStyle='rgba(167,139,250,.75)';g.beginPath();st=false;mm.signal.forEach((v,i)=>{if(v==null)return;st?g.lineTo(x(i),yy(v)):g.moveTo(x(i),yy(v));st=true});g.stroke();latestExtra.push(`MACD ${fmt(mm.line.at(-1),2)}`)}
  if(this.opts.atr){const aa=atr(b),v=aa.at(-1);latestExtra.push(`ATR14 ${fmt(v,2)}`)}
  if(this.hover!=null){const i=this.hover,z=b[i],xx=x(i);g.strokeStyle='rgba(220,252,255,.28)';g.beginPath();g.moveTo(xx,padT);g.lineTo(xx,h-padB);g.stroke();g.fillStyle='rgba(3,10,15,.94)';g.strokeStyle='rgba(124,234,255,.25)';g.lineWidth=1;const tw=Math.min(280,w-16),tx=Math.min(w-tw-8,Math.max(6,xx+10)),ty=18;g.fillRect(tx,ty,tw,84);g.strokeRect(tx,ty,tw,84);g.fillStyle='#cfeaf1';g.font='11px ui-monospace';g.textAlign='left';g.fillText(z.date,tx+8,ty+16);g.fillStyle='#8dabb8';g.fillText(`O ${fmt(z.open)}  H ${fmt(z.high)}`,tx+8,ty+34);g.fillText(`L ${fmt(z.low)}  C ${fmt(z.close)}`,tx+8,ty+50);g.fillText(`Volume ${Math.round(z.volume).toLocaleString()}`,tx+8,ty+68)}
  const last=b.at(-1),legend=[`C ${fmt(last.close)}`,this.opts.sma20?`SMA20 ${fmt(s20.at(-1))}`:null,this.opts.sma50?`SMA50 ${fmt(s50.at(-1))}`:null,this.opts.vwap?`VWAP ${fmt(last.vwap)}`:null,...(compLegend?[compLegend]:[]),...latestExtra].filter(Boolean);if(this.legend)this.legend.innerHTML=legend.map((v,i)=>`<span>${i?'<span class="ex-badge model">CALC</span>':''}<span class="chart-value">${v}</span></span>`).join('');
 }
}
window.RecoveryResearchChart=RecoveryResearchChart;
window.RecoveryIndicators={sma,ema,rsi,atr,macd};
})();

