const CACHE='recovery-os-movement-v8';
const STATIC=['./movement-model.js?v=20260922-movement1','./movement-ui.js?v=20260922-movement1','./movement.css?v=20260922-movement1','./data-freshness.js?v=20260922-refresh1','./refresh-controller.js?v=20260922-refresh1','./research-transport.js?v=20260922-refresh1','./data/information/connectors.json','./information-bridge.js','./information-model.js?v=20260922-movement1','./information-store.js','./information-ui.js?v=20260922-movement1','./information-world.js?v=20260922-movement1','./information.css?v=1','./data/information/coverage.json','./data/information/providers.json','./data/information/health.json','./data/information/source-review.json','./','./index.html','./styles.css','./explorer.css','./tradingview-mode.css','./app.js?v=20260922-refresh1','./research-chart.js','./explorer-prod-0.js','./explorer-prod-1.js','./explorer-prod-2.js','./explorer-prod-3.js','./explorer-prod-4.js','./explorer-prod-5.js','./explorer-prod-6.js?v=20260922-refresh1','./explorer-prod-7.js','./explorer-prod-8.js?v=20260922-refresh1','./explorer-prod-9.js','./explorer-prod-10.js','./free-hybrid.js?v=20260922-refresh1','./research-model.js?v=20260922-refresh1','./research-world.css?v=20260922-refresh1','./research-universe.css?v=20260922-refresh1','./research-evidence.js?v=20260922-refresh1','./research-universe.js','./world-renderer.js','./market-world.js?v=20260922-movement1','./market-world.css?v=20260922-refresh1','./market-atlas.js?v=20260922-refresh1','./data/market-atlas/index.json','./vendor/three.module.min.js','./data/open-research/index.json','./data/open-research/directory.json','./data/open-research/macro.json','./data/research/index.json','./manifest.webmanifest','./assets/icon.svg','./data/recovery-os.json','./data/research-seed.json','./data/research-seed-aapl-extra.json','./data/symbols-seed.json','./data/provider-capabilities.json'];
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>Promise.all(STATIC.filter(x=>!x.endsWith('.json')).map(x=>c.add(x).catch(()=>{})))).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('recovery-os-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{
  const request=event.request,url=new URL(request.url);
  if(request.method!=='GET'||url.origin!==self.location.origin)return;
  if(url.pathname.includes('/tests/'))return;
  const key=url.origin+url.pathname;
  const fresh=request.mode==='navigate'||['document','script','style'].includes(request.destination)||url.pathname.endsWith('.json');
  const offline=async()=>await caches.match(request,{ignoreSearch:true})||await caches.match(key,{ignoreSearch:true})||new Response('This page is unavailable offline.',{status:503,headers:{'Content-Type':'text/plain'}});
  const network=async()=>{const response=await fetch(request,{cache:fresh?'no-cache':'default'});if(response.ok){const copy=response.clone();event.waitUntil(caches.open(CACHE).then(cache=>cache.put(key,copy)).catch(()=>{}))}return response};
  event.respondWith(fresh?network().catch(offline):caches.match(key).then(cached=>cached||network().catch(offline)));
});
