const test=require('node:test'),assert=require('node:assert/strict');
const F=require('../information-model.js'),M=require('../movement-model.js');
const now='2026-09-22T22:00:00Z';
const source={provider:'Example issuer',url:'https://example.com/release',sourceType:'ISSUER',publishedAt:'2026-09-22T13:00:00Z',retrievedAt:'2026-09-22T15:00:00Z',timestampPrecision:'INSTANT'};
function event(overrides={}){return {...F.event('announcements','Company raises guidance',{ticker:'TEST',publishedAt:source.publishedAt,detectedAt:source.retrievedAt,evidence:[F.source(source)],sourceType:'ISSUER'},{eventTimeKnown:false}),...overrides};}
function dossier({quoteAt=now,change=3,bars=[],events=[]}={}){return F.normalize({profile:{ticker:'TEST',name:'Test Corp',sector:'Technology',currency:'USD'},quote:{price:103,changePct:change,asOf:quoteAt,dataState:'DATED MARKET SNAPSHOT',currency:'USD'},priceSource:{publisher:'Finance provider',url:'https://example.com/quotes',date:quoteAt,retrievedAt:quoteAt},barSource:{publisher:'History provider',url:'https://example.com/history',currency:'USD'},retrievedAt:now,bars,news:[],health:[]});}
const bars=[{date:'2026-09-14',close:90},{date:'2026-09-15',close:100},{date:'2026-09-21',close:102},{date:'2026-09-22',close:105}];
test('today is New York day, including DST transition',()=>{assert.equal(M.windowFor('today',now).start,'2026-09-22T04:00:00.000Z');const w=M.windowFor('today','2026-03-08T22:00:00Z');assert.equal(w.start,'2026-03-08T05:00:00.000Z');assert.equal(M.windowFor('today',F.dayEnd('2026-09-22')).day,'2026-09-22');});
test('daily quote keeps provider change without inventing reference price',()=>{const r=M.analyze(dossier(),{now});assert.equal(r.move.pct,3);assert.equal(r.move.from,null);assert.equal(r.move.basis,'reported');assert.match(r.move.reason,/reference close time/);});
test('old quote is not today; missing weekly history is not fabricated',()=>{const d=dossier({quoteAt:'2026-09-11T20:00:00Z',bars:[{date:'2026-09-11',close:100}]});assert.equal(M.analyze(d,{now}).move.pct,null);assert.equal(M.analyze(d,{now,period:'week'}).move.pct,null);});
test('week uses compatible dated closes and states actual endpoints',()=>{const d=dossier({bars});const r=M.analyze(d,{period:'week',cutoff:F.dayEnd('2026-09-22')});assert.equal(r.move.pct,5.000000000000004);assert.equal(r.move.from,F.dayEnd('2026-09-15'));assert.equal(r.move.to,F.dayEnd('2026-09-22'));});
test('no old or future headline enters today; same-day evidence is not causal',()=>{const d=dossier();d.events=[event(),event({id:'old',publishedAt:'2026-09-11T13:00:00Z'}),event({id:'future',publishedAt:'2026-09-23T13:00:00Z'})];const r=M.analyze(d,{now});assert.equal(r.evidence.length,1);assert.equal(r.verdict,'No confirmed catalyst found');assert.equal(r.evidence[0].label,'Possible contributor');assert.equal(r.evidence[0].eventAt,null);assert.match(r.evidence[0].timing,/onset.*unknown/);});
test('date-only publication is withheld until publication day ends',()=>{const d=F.normalize({profile:{ticker:'TEST'},news:[{title:'New filing',url:'https://example.com/day',published:'2026-09-22',publisher:'Issuer',sourceType:'OFFICIAL'}]});assert.equal(M.analyze(d,{now}).evidence.length,0);assert.equal(M.analyze(d,{cutoff:F.dayEnd('2026-09-22')}).evidence.length,1);});
test('historical observed mode excludes evidence retrieved later',()=>{const d=dossier();d.events=[event({detectedAt:'2026-09-23T13:00:00Z'})];assert.equal(M.analyze(d,{cutoff:now,mode:'observed'}).evidence.length,0);assert.equal(M.analyze(d,{cutoff:now,mode:'public'}).evidence.length,1);});
test('updated article version is unavailable before its update',()=>{const d=F.normalize({profile:{ticker:'TEST'},news:[{title:'Revised report',url:'https://example.com/report',published:'2026-09-22T12:00:00Z',updatedAt:'2026-09-23T12:00:00Z',publisher:'News'}]});assert.equal(M.analyze(d,{cutoff:now}).evidence.length,0);});
test('future prices never leak into replay',()=>{const d=dossier({bars:[...bars,{date:'2026-09-23',close:999}]});const r=M.analyze(d,{cutoff:F.dayEnd('2026-09-21')});assert.equal(r.move.quoteAt,null);assert.ok(r.timeline.every(x=>x.at<=r.window.end));assert.ok(!JSON.stringify(r.move).includes('999'));});
test('unsafe links rejected, tracking URL duplicates collapsed',()=>{const d=dossier();d.events=[event(),event({id:'dup',evidence:[F.source({...source,url:source.url+'?utm_source=rss#top'})]}),event({id:'bad',evidence:[{...source,url:'javascript:alert(1)'}]})];assert.equal(M.analyze(d,{now}).evidence.length,1);});
test('reported explanations remain separate from confirmed facts',()=>{const e=event({title:'Shares rise after earnings beat',category:'news',sourceType:'SECONDARY_NEWS'});const a=M.mechanism(e);assert.equal(a.label,'Reported explanation');assert.equal(a.factLabel,'Reported information');});
test('conflicting factors retained and direction does not come from stock return',()=>{const d=dossier({change:-3});d.events=[event(),event({id:'bear',title:'Company cuts outlook',evidence:[F.source({...source,url:'https://example.com/cut'})]})];const r=M.analyze(d,{now});assert.deepEqual(new Set(r.evidence.map(x=>x.direction)),new Set(['Bullish factor','Bearish factor']));});
test('same-day event after observed price cannot explain earlier price',()=>{const d=dossier({quoteAt:'2026-09-22T12:00:00Z'});d.events=[event()];const r=M.analyze(d,{now});assert.equal(r.evidence[0].strength,'Outside observed move');assert.match(r.evidence[0].timing,/cannot explain/);});
test('benchmark mismatches suppressed; aligned returns compare',()=>{const a={pct:3,basis:'closes',from:'a',to:'b',source:{currency:'USD'}},b={...a,pct:1};assert.equal(M.compare(a,b).excess,2);assert.equal(M.compare(a,{...b,to:'c'}).comparable,false);assert.equal(M.compare(a,{...b,source:{currency:'EUR'}}).comparable,false);assert.equal(M.compare({...a,basis:'reported'},{...b,basis:'reported'}).comparable,false);});
test('analysis does not mutate source evidence or tracker',()=>{const d=dossier({bars});d.events=[event()];d.tracker={score:71,discoveryPrice:10};const before=JSON.stringify(d);M.analyze(d,{now});assert.equal(JSON.stringify(d),before);});
