import {test} from 'node:test';import assert from 'node:assert/strict';import {createProviderClient,retryDelay} from '../backend/cloudflare/provider-client.mjs';import {factsToRows,informationRoute} from '../backend/cloudflare/information.mjs';
function store(){const cache=new Map(),uses=new Map(),health=new Map(),cooldown=new Map();return{cache,uses,healthRecords:health,async cacheGet(k){return cache.get(k)},async cachePut(k,v){cache.set(k,v)},async reserve(p,b,max){const k=p+b,n=uses.get(k)||0;if(n>=max)return false;uses.set(k,n+1);return true},async cooldown(p){return cooldown.get(p)||0},async setCooldown(p,v){cooldown.set(p,v)},async health(p,h){health.set(p,{...health.get(p),...h})}}}
const args={provider:'sec',url:'https://data.sec.gov/submissions/CIK0000910521.json',ttl:1,limit:2,windowSeconds:1};
test('concurrent callers share one request and retain metadata',async()=>{const s=store();let calls=0;const c=createProviderClient({storage:s,fetcher:async()=>{calls++;return Response.json({cik:910521})}});const [a,b]=await Promise.all([c(args),c(args)]);assert.equal(calls,1);assert.deepEqual(a,b);assert.ok(a.lastSuccessAt)});
test('cache hit does not consume another provider rate token',async()=>{const s=store();let calls=0;const c=createProviderClient({storage:s,fetcher:async()=>{calls++;return Response.json({ok:true})}});await c(args);assert.equal((await c(args)).cache,'HIT');assert.equal(calls,1)});
test('429 honors Retry-After, persists cooldown and returns last record unchanged',async()=>{const s=store();let now=1000000,calls=0;const c=createProviderClient({storage:s,clock:()=>now,fetcher:async()=>++calls===1?Response.json({value:42}):new Response('',{status:429,headers:{'Retry-After':'120'}})});const first=await c(args);now+=2000;const next=await c(args);assert.equal(next.data.value,42);assert.equal(next.retrievedAt,first.retrievedAt);assert.equal(next.cache,'STALE');assert.equal(await s.cooldown('sec'),now+120000);await c(args);assert.equal(calls,2)});
test('rate budget is shared across cache keys',async()=>{const s=store();let calls=0;const c=createProviderClient({storage:s,clock:()=>1000000,fetcher:async()=>{calls++;return Response.json({ok:true})}});await c({...args,url:args.url+'?a=1'});await c({...args,url:args.url+'?a=2'});await assert.rejects(c({...args,url:args.url+'?a=3'}),e=>e.code==='LOCAL_RATE_BUDGET');assert.equal(calls,2)});
test('403 access failures are not repeatedly retried',async()=>{const s=store();let calls=0;const c=createProviderClient({storage:s,fetcher:async()=>{calls++;return new Response('secret must not escape',{status:403})}});await assert.rejects(c(args),e=>!e.message.includes('secret')&&e.code==='ACCESS_OR_ENTITLEMENT_DENIED');await assert.rejects(c(args));assert.equal(calls,1)});
test('5xx retries are bounded then fail',async()=>{let calls=0;const c=createProviderClient({storage:store(),sleep:async()=>{},fetcher:async()=>{calls++;return new Response('',{status:503})}});await assert.rejects(c({...args,limit:10}));assert.equal(calls,3)});
test('payload size and schema errors cannot replace last verified cache',async()=>{const s=store();let now=1e6,n=0;const c=createProviderClient({storage:s,clock:()=>now,fetcher:async()=>++n===1?Response.json({price:10}):Response.json({price:'bad'})});await c({...args,validate:d=>typeof d.price==='number'});now+=2000;const r=await c({...args,validate:d=>typeof d.price==='number'});assert.equal(r.data.price,10);assert.equal(r.cache,'STALE')});
test('source allowlist rejects arbitrary request URLs',async()=>{const c=createProviderClient({storage:store(),fetcher:async()=>{throw Error('must not fetch')}});await assert.rejects(c({...args,url:'https://evil.example/'}),e=>e.code==='SOURCE_NOT_APPROVED')});
test('Retry-After accepts seconds and HTTP date',()=>{assert.equal(retryDelay('20',0),20000);assert.equal(retryDelay('Thu, 01 Jan 1970 00:01:00 GMT',0),60000)});
test('facts converter keeps actual date scopes and filing revisions',()=>{const facts={facts:{'us-gaap':{Revenues:{units:{USD:[{val:100,start:'2026-01-01',end:'2026-03-31',filed:'2026-05-01',fp:'Q1',fy:2026,form:'10-Q',accn:'abc'},{val:105,start:'2026-01-01',end:'2026-03-31',filed:'2026-05-02',fp:'Q1',fy:2026,form:'10-Q',accn:'def'}]}}}}};const rows=factsToRows(facts,'910521');assert.equal(rows.quarterly.length,2);assert.equal(rows.quarterly[0].filingDate,'2026-05-02')});
test('information API blocks writes and unapproved origins',async()=>{let r=await informationRoute(new Request('https://example.com/api/information/stock/DECK',{method:'POST'}),{});assert.equal(r.status,405);r=await informationRoute(new Request('https://example.com/api/information/health',{headers:{Origin:'https://evil.example'}}),{});assert.equal(r.status,403)});
test('missing durable D1 is a structured limitation, not a fake live response',async()=>{const r=await informationRoute(new Request('https://example.com/api/information/health'),{});assert.equal(r.status,503);assert.equal((await r.json()).error,'D1_NOT_CONFIGURED')});
test('approved browser origin can preflight read-only information requests',async()=>{const r=await informationRoute(new Request('https://api.example/api/information/stock/DECK',{method:'OPTIONS',headers:{Origin:'https://lanqston.github.io'}}),{});assert.equal(r.status,204);assert.match(r.headers.get('Access-Control-Allow-Methods'),/GET/);assert.doesNotMatch(r.headers.get('Access-Control-Allow-Methods'),/POST|PUT/)});
test('403 on directory endpoint does not block unrelated SEC data',async()=>{const c=createProviderClient({storage:store(),fetcher:async url=>url.includes('www.sec.gov')?new Response('',{status:403}):Response.json({cik:1})});await assert.rejects(c({...args,url:'https://www.sec.gov/files/company_tickers_exchange.json',limit:10}));assert.equal((await c({...args,limit:10})).data.cik,1)});
test('network failure retries then succeeds within the rate budget',async()=>{let n=0;const c=createProviderClient({storage:store(),sleep:async()=>{},fetcher:async()=>{if(++n<3)throw new TypeError('temporary');return Response.json({ok:true})}});assert.equal((await c({...args,limit:10})).data.ok,true);assert.equal(n,3)});
test('Alpha Vantage HTTP-200 quota message is never cached as market data',async()=>{const s=store();let n=0;const c=createProviderClient({storage:s,fetcher:async()=>{n++;return Response.json({Information:'Daily quota'})}});const a={...args,provider:'alpha-vantage',url:'https://www.alphavantage.co/query?apikey=private'};await assert.rejects(c(a),e=>e.status===429);await assert.rejects(c(a));assert.equal(n,1);assert.equal(s.cache.size,0);assert.ok(!JSON.stringify([...s.healthRecords]).includes('private'))});
