/* Provider HTTP reliability. No arbitrary URLs, query secrets or unbounded retries. */
export class ProviderError extends Error{constructor(code,provider,status=503,extra={}){super(code);this.code=code;this.provider=provider;this.status=status;Object.assign(this,extra)}}
export function retryDelay(header,now=Date.now()){const seconds=Number(header);if(header&&Number.isFinite(seconds))return Math.max(0,seconds*1000);const at=Date.parse(header||'');return Number.isFinite(at)?Math.max(0,at-now):60000}
export function createProviderClient({storage,fetcher=fetch,clock=()=>Date.now(),sleep=ms=>new Promise(r=>setTimeout(r,ms))}){const pending=new Map();return async function request({provider,url,headers={},ttl=3600,limit=5,windowSeconds=60,maxBytes=12e6,validate=x=>x&&typeof x==='object'}){const u=new URL(url),allowed={sec:['data.sec.gov','www.sec.gov'],massive:['api.massive.com'],'alpha-vantage':['www.alphavantage.co']};if(u.protocol!=='https:'||!allowed[provider]?.includes(u.hostname)||u.username||u.password)throw new ProviderError('SOURCE_NOT_APPROVED',provider,400);const safe=new URL(url);for(const key of ['apikey','apiKey','token','key'])safe.searchParams.delete(key);const key=provider+':'+safe.href;if(pending.has(key))return pending.get(key);const task=(async()=>{const now=clock(),cached=await storage.cacheGet(key);if(cached?.expires>now)return{...cached.result,cache:'HIT'};let failure;const cooldown=await storage.cooldown(provider);if(cooldown>now)failure=new ProviderError('PROVIDER_COOLDOWN',provider,429,{retryAt:new Date(cooldown).toISOString()});
for(let attempt=0;attempt<3&&!failure;attempt++){if(!await storage.reserve(provider,Math.floor(clock()/(windowSeconds*1000)),limit)){failure=new ProviderError('LOCAL_RATE_BUDGET',provider,429,{retryAt:new Date((Math.floor(clock()/(windowSeconds*1000))+1)*windowSeconds*1000).toISOString()});break}const attemptedAt=new Date(clock()).toISOString();try{const response=await fetcher(url,{headers,signal:AbortSignal.timeout(12000),redirect:'error'});if(!response.ok){const status=response.status,backoff=status===429?retryDelay(response.headers.get('Retry-After'),clock()):status===403?3600000:0;if(backoff)await storage.setCooldown(provider,clock()+backoff);const e=new ProviderError(status===429?'UPSTREAM_RATE_LIMIT':status===403?'ACCESS_OR_ENTITLEMENT_DENIED':'UPSTREAM_HTTP_ERROR',provider,status,{lastAttemptAt:attemptedAt,providerStatus:status,retryAt:backoff?new Date(clock()+backoff).toISOString():null});if(status>=500&&attempt<2){await sleep(250*2**attempt);continue}throw e}const length=Number(response.headers.get('Content-Length')||0);if(length>maxBytes)throw new ProviderError('PAYLOAD_TOO_LARGE',provider,502);let chunks=[],bytes=0;const reader=response.body?.getReader();if(!reader)throw new ProviderError('EMPTY_RESPONSE',provider,502);for(;;){const {done,value}=await reader.read();if(done)break;bytes+=value.length;if(bytes>maxBytes){await reader.cancel();throw new ProviderError('PAYLOAD_TOO_LARGE',provider,502)}chunks.push(value)}const buffer=new Uint8Array(bytes);let offset=0;for(const c of chunks){buffer.set(c,offset);offset+=c.length}let data;try{data=JSON.parse(new TextDecoder().decode(buffer))}catch{throw new ProviderError('INVALID_JSON',provider,502)}if(!validate(data))throw new ProviderError('SCHEMA_VALIDATION_FAILED',provider,502);const result={data,provider,sourceURL:safe.href,retrievedAt:new Date(clock()).toISOString(),lastSuccessAt:attemptedAt,lastAttemptAt:attemptedAt,cache:'MISS',bytes,errors:[]};await storage.cachePut(key,{expires:clock()+ttl*1000,result});await storage.health(provider,{status:'Current',lastSuccessAt:attemptedAt,lastAttemptAt:attemptedAt,bytes,error:null});return result}catch(e){failure=e instanceof ProviderError?e:new ProviderError(e.name==='TimeoutError'?'UPSTREAM_TIMEOUT':'UPSTREAM_NETWORK_ERROR',provider,503,{lastAttemptAt:attemptedAt});}}
const error={code:failure?.code||'UPSTREAM_FAILURE',provider,status:failure?.status||503,lastAttemptAt:failure?.lastAttemptAt||new Date(clock()).toISOString(),retryAt:failure?.retryAt||null};await storage.health(provider,{status:error.status===429?'Rate limited':'Error',lastAttemptAt:error.lastAttemptAt,error});if(cached)return{...cached.result,cache:'STALE',lastAttemptAt:error.lastAttemptAt,errors:[error]};throw new ProviderError(error.code,provider,error.status,error)})();pending.set(key,task);try{return await task}finally{pending.delete(key)}}}
export function d1Storage(db){return{
 async cacheGet(key){const row=await db.prepare('SELECT payload, expires FROM fabric_cache WHERE key=?').bind(key).first();return row?{expires:row.expires,result:JSON.parse(row.payload)}:null},
 async cachePut(key,v){await db.prepare('INSERT INTO fabric_cache(key,payload,expires) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET payload=excluded.payload,expires=excluded.expires').bind(key,JSON.stringify(v.result),v.expires).run()},
 async reserve(provider,bucket,limit){const row=await db.prepare('INSERT INTO fabric_usage(provider,bucket,used) VALUES(?,?,1) ON CONFLICT(provider,bucket) DO UPDATE SET used=used+1 WHERE used<? RETURNING used').bind(provider,bucket,limit).first();return !!row},
 async cooldown(provider){return(await db.prepare('SELECT cooldown_until FROM fabric_provider_health WHERE provider=?').bind(provider).first())?.cooldown_until||0},
 async setCooldown(provider,until){await db.prepare('INSERT INTO fabric_provider_health(provider,cooldown_until) VALUES(?,?) ON CONFLICT(provider) DO UPDATE SET cooldown_until=MAX(cooldown_until,excluded.cooldown_until)').bind(provider,until).run()},
 async health(provider,h){const old=await db.prepare('SELECT payload FROM fabric_provider_health WHERE provider=?').bind(provider).first();const value={...JSON.parse(old?.payload||'{}'),...h};await db.prepare('INSERT INTO fabric_provider_health(provider,payload) VALUES(?,?) ON CONFLICT(provider) DO UPDATE SET payload=excluded.payload').bind(provider,JSON.stringify(value)).run()}
}}
